- ClientTester/MultiplayerClient.cs
- NitroxClient/Communication/Client.cs
- NitroxClient/Communication/Packets/Processors/DisconnectProcessor.cs
- NitroxClient/GameLogic/PlayerGameObjectManager.cs
- NitroxClient/MonoBehaviours/Multiplayer.cs
- NitroxClient/NitroxClient.csproj
- NitroxModel/NitroxModel.csproj
- NitroxModel/Packets/Disconnect.cs
- NitroxModel/Tcp/Connection.cs
- NitroxServer/Listener.cs
Fix server crashes due to network read/write failures, Socket failures. Remove player model when disconnected.
> Networking Enhancements

- .gitignore
- ClientTester/ClientTester.csproj
- DevVars.targets.example
- NitroxClient/NitroxClient.csproj
- NitroxModel/NitroxModel.csproj
- NitroxPatcher/NitroxPatcher.csproj
- NitroxServer/NitroxServer.csproj
- NitroxTest/NitroxTest.csproj
- SharedConfig.targets
Uses some MSBuild targets to check whether the game is installed in the default Steam location. If not, copies a targets file (whose changes will be ignored) where a developer can enter the alternative location.
(The target file overrides the default location if it exists).
Because the dependencies and projects will end up in a single folder anyway, I merged all the bin folders into one to prevent all these duplicates from existing in different folders. This commit can be removed if this behavior is not desired.
Final commit contains another MSBuild target to copy generated assemblies to the Subnautica managed folder. I'm still checking out automated injection, so let me know if that's something we want.
The wiki setup page should be updated to reflect these changes.
> Unified project config

- NitroxClient/ApiHelper.cs
- NitroxClient/MonoBehaviours/Multiplayer.cs
- NitroxPatcher/Main.cs
- NitroxPatcher/Patches/ClipMapManager_HideEntities_Patch.cs
- NitroxTest/Patcher/Patches/BuilderPatchTest.cs
- NitroxTest/Patcher/Patches/ClipMapManager_HideEntities_PatchTest.cs
- NitroxTest/Patcher/Patches/ClipMapManager_ShowEntities_PatchTest.cs
- NitroxTest/Patcher/Patches/Constructable_Construct_PatchTest.cs
- NitroxTest/Patcher/Test/PatchTestHelper.cs
Checks for nullity on `VoxelandChunk`s returned by `get_chunks`.
> Fix NRE in HideEntities patch.

- ClientTester/MultiplayerClient.cs
- ClientTester/Program.cs
- NitroxClient/Communication/ChunkAwarePacketReceiver.cs
- NitroxClient/Communication/Client.cs
- NitroxClient/Communication/Packets/Processors/VehicleMovementProcessor.cs
- NitroxClient/GameLogic/PlayerGameObjectManager.cs
- NitroxClient/MonoBehaviours/Multiplayer.cs
- NitroxModel/Tcp/Connection.cs
- NitroxServer/Listener.cs
Gets rid of all the warnings and 'informative' messages that are shown on the current master branch.
Some are C#6/7 specific, so we should discuss which version we want to support at a minimum. I'll remove those changes once we've settled on a version. Some of the messages are about improper naming, as currently `lowerCamelCasing` is sometimes used for private methods, whilst visual studio is set to `UpperCamelCasing` to default. IMHO it doesn't matter which one we use, as long as we stay consistent. A styleguide would be really helpful (perhaps a config for VS if such a thing is even possible?).
Also, I think we should enforce that PR code is free of warnings. Those on the current master branch are harmless (unused variables), but more serious ones will get lost in a pile of these. And …
> Fixed warnings and messages.

- .gitmodules
Git stores this configuration somewhere internally, hence why it kept working for me. I checked this with a fresh clone and it resolves the issue.
> Fixed relative submodule.

- NitroxClient/GameLogic/Logic.cs
- NitroxModel/Helper/SteamFinder.cs
- NitroxServer/Serialization/BatchCellsParser.cs
For platform-independent filename support. And to reduce confusion when not all paths have a trailing separator.
> More Path.Combine.

- .editorconfig
After a while of using and evaluating it turns out the errors for style violations cause more confusion than they do good while debugging. All errors have been reduced to warnings, especially since the Harmony subproject violates a bunch of them. This may however make them harder to spot - I have not yet found a way to exclude Harmony from checking, except for compiling the project once and unloading it (this may however cause developers to miss potential updates in the future, as it stays unloaded on subsequent solution loads).
The "new" but highly skilled contributors do use/like C# features such as `var` and `?.` - I think we may want to (read: should) reconsider the current policy.
Visual Studio may properly read from this file. I checked my own `Tools > Options... > style` and all …
> Use warnings instead of errors for style violations.

- NitroxClient/MonoBehaviours/Multiplayer.cs
- NitroxPatcher/NitroxPatcher.csproj
- NitroxPatcher/Patches/Persistent/EscapePodFirstUseCinematicsController_Initialize_Patch.cs
Implements #122 
Introductory sequence is disabled in multiplayer, and first time escape pod exit cutscenes don't play in multiplayer either (and the creatures aren't spawned).
Intro and pod cutscenes play as normal in singleplayer.
> Disable intro sequences in multiplayer

- NitroxServer/Communication/UdpServer.cs
- NitroxServer/MainWindow.xaml
- NitroxServer/MainWindow.xaml.cs
- NitroxServer/Server.cs
I added a closing event on the main window to call the shutdown of the NetworkPeer and stop the listen thread. This solves the issue of the server still running when the window is closed.
> Graceful server shutdown

- NitroxModel/Discovery/InstallationFinders/SteamGameRegistryFinder.cs
On linux and mono, the Steam registry lookup would return null which would crash the process.
```
[Nitrox] E: System.ArgumentNullException: Value cannot be null.
Parameter name: path1
at System.IO.Path.Combine (System.String path1, System.String path2) [0x00003] in <3d1438d9da1e4fe0b915f807d1ba56bd>:0
at NitroxModel.Discovery.InstallationFinders.SteamGameRegistryFinder.FindGame (System.Collections.Generic.List`1[T] errors) [0x0000f] in <484753777b4b4c1ea501fed6c0b21452>:0
```
This proposal ensures that this does not happen and that in the case that the Steam registry can not be found for whatever reason, the application continues to look for the game files from other sources.
I tested this and the server works on linux after this change, however there are still some unrelated issues …
> Added a null check to SteamGameRegistryFinder

- NitroxServer/IpLogger.cs
I always got both messages:
```
If using port forwarding, use this IP: xxx.xxx.xxx.xxx
Could not get your external IP. You are on your own...
```
> Avoid "you are on your own" warning on success

- NitroxPatcher/NitroxPatcher.csproj
- NitroxPatcher/Patches/BaseAddBulkheadGhost_UpdatePlacement_Patch.cs
Mimicked the BaseAddModuleGhost Nitrox patch to use the MutiplayerBuilder instead of the Player main subroot for the UpdatePlacement.
> Bulkhead UpdatePlacement patch

- NitroxPatcher/NitroxPatcher.csproj
- NitroxPatcher/Patches/Stalker_CheckLoseTooth_Patch.cs
As-is, titanium, scrap, seamoth and prawn suit drop at 15%, live things drop at 5%.
> Patched CheckLoseTooth with hard-coded hardness values

- NitroxClient/GameLogic/Spawning/DefaultEntitySpawner.cs
This allows movable objects spawned by the server to be moved so players can progress further through the story ie boxes blocking the aurora entries.
Only movable objects can be moved... I'm not sure if this affects anything else game related i did some limited testing and seems to be fine.
> Bug with server spawned objects not being movable

- NitroxServer/Serialization/BatchCellsParser.cs
The ParseFiles silently failed to find `batch-cells-1-16-8baked-.bin` . Modified so that it correctly creates `baked-batch-cells-*-*-*.bin`.
However, the parsing of baked- throws an exception.
```
[Nitrox] I: Parsing c:/program files (x86)/steam\steamapps\common\Subnautica\SNUnmanagedData\Build18\CellsCache\baked-batch-cells-12-18-11.bin
[Nitrox] I: Exception while processing packet:
[CellVisibilityChanged 
| Added: 
[AbsoluteEntityCell Position: 0,32,-352 BatchId: 12,19,10 CellId: 4,1,3 Level: 3 ]
[...]
[AbsoluteEntityCell Position: -160,-128,-352 BatchId: 11,18,10 CellId: 4,1,3 Level: 2 ]
| Removed: 
[AbsoluteEntityCell Position: -32,-128,-256 BatchId: 12,18,11 CellId: 3,1,1 Level: 1 ]
[...]
[AbsoluteEntityCell Position: -64,-128,-288 BatchId: 12,18,11 CellId: 2,1,0 Level: 1 ]
| …
```
> fix FileParser to suport filename prefix

- NitroxModel/Packets/ServerCommand.cs
- NitroxPatcher/Patches/DayNightCycle_OnConsoleCommand_day_Patch.cs
- NitroxPatcher/Patches/DayNightCycle_OnConsoleCommand_night_Patch.cs
As requested in #645 the day/night commands from the DevConsole now send the ServerCommand packet.
> Sending server commands for day/night on DevConsole

- NitroxLauncher/Main.cs
- NitroxLauncher/NitroxLauncher.csproj
- NitroxLauncher/packages.config
I really like the new Launcher, but i had some issues with it: There was always an BadImageFormat Exception with the **discord-rpc.dll**. It seems that this dll is missing some version info, so AssemblyName.GetAssemblyName will fail here when trying to get the version.
This PR adds a workaround for that.
> Fix issue with discord-rpc.dll version is missing / cannot be determined

- NitroxClient/GameLogic/MovementHelper.cs
- NitroxClient/GameLogic/RemotePlayer.cs
- NitroxClient/MonoBehaviours/PlayerMovement.cs
Fixes https://github.com/SubnauticaNitrox/Nitrox/issues/128
Fixes https://github.com/SubnauticaNitrox/Nitrox/issues/794
Address Y-offset issues by removing the broken "interpolation"/"smoothing".
Also, make rotation relative to the subroot (just like positioning). This is to keep the player properly oriented when the subroot moves without (timely) receiving position updates from other players in this subroot.
We need to make a light-weight "RigidBody" controller, since it's only used to integrate velocities after all. The current implementation will keep interpolating the velocity causing players to fly away when no packets are received. The new implementation should apply some kind of smoothing towards the end and hold the player stationary when no packets are received for a prolonged …
> Fix player sinking and relative rotation

- NitroxClient/NitroxClient.csproj
- NitroxClient/Properties/Resources.Designer.cs
- NitroxLauncher/NitroxLauncher.csproj
- NitroxModel-Subnautica/NitroxModel-Subnautica.csproj
- NitroxModel/NitroxModel.csproj
- NitroxPatcher/App.config
- NitroxPatcher/NitroxPatcher.csproj
- NitroxPatcher/Patches/BaseDeconstructable_Deconstruct_Patch.cs
- NitroxPatcher/Patches/Persistent/PAXTerrainController_LoadAsync_Patch.cs
- NitroxServer-Subnautica/NitroxServer-Subnautica.csproj
- NitroxServer/NitroxServer.csproj
- NitroxTest/NitroxTest.csproj
Updates the projects to .Net Framework 4.0 and removes references to libraries that no longer exist.
> Unity 2019 Upgrade

- NitroxLauncher/LauncherLogic.cs
Adjusted mono syncing mono assemblys combined path. 
Due to location of mono folder changing to root subnautica folder from Subnautica_Data folder
Fixes #848 #862
> Adjusted mono path to new location

- NitroxClient/GameLogic/InitialSync/PlayerPositionInitialSyncProcessor.cs
Not ideal pretty sure that there is some cause but can't find anything in the code or assemblies that seems to have any effect.
Feel free to throw it out.
> Fixed player initial spawn from random to inside escapepod

- NitroxLauncher/ServerPage.xaml
- NitroxLauncher/ServerPage.xaml.cs
The embedded server page in the NitroxLauncher needs more work. The way it displays text is very bad on performance. Until this is fixed I recommend just launching the cmd by default.
> Changed default server start option to 'console window'

- .gitmodules
Removed Harmony submodule as no longer needed due to using the nuget package now.
> Removed Harmony module from .gitmodules

- NitroxClient/Debuggers/BaseDebugger.cs
- NitroxClient/Debuggers/SceneDebugger.cs
- NitroxClient/MonoBehaviours/NitroxDebugManager.cs
A few changes to the SceneDebugger:
- Changed global position and rotation to a read-only field
- Changed rotation value fields from quaternion to euler-angles
- Added an option to filter (System/mscorlib and UnityEngine) the "invokable" methods
- Reordered transform values
- Position of all Debuggers resets if the F7 key is pressed to prevent loosing the window
- Bug fixes
> SceneDebugger update

- AssemblyInfoCommon.cs
- NitroxClient/NitroxClient.csproj
- NitroxClient/Properties/AssemblyInfo.cs
- NitroxLauncher/NitroxLauncher.csproj
- NitroxLauncher/Properties/AssemblyInfo.cs
- NitroxModel-Subnautica/NitroxModel-Subnautica.csproj
- NitroxModel-Subnautica/Properties/AssemblyInfo.cs
- NitroxModel/NitroxModel.csproj
- NitroxModel/Properties/AssemblyInfo.cs
- NitroxPatcher/NitroxPatcher.csproj
- NitroxPatcher/Properties/AssemblyInfo.cs
- NitroxServer-Subnautica/NitroxServer-Subnautica.csproj
- NitroxServer/NitroxServer.csproj
- NitroxServer/Properties/AssemblyInfo.cs
- NitroxTest/NitroxTest.csproj
- NitroxTest/Properties/AssemblyInfo.cs
This change supports rolling the version number for all projects in a single file. This is useful for multi-assembly solutions where each has a common version number as well as other attributes (e.g. copyright, etc).
"AssemblyInfoCommon.cs" is placed at the root of the solution. It is then linked (Add as link) into each project and collocated with the AssemblyInfo.cs (at .\Properties). AssemblyInfoCommon.cs holds the common values while each AssemblyInfo.cs retains the unique ones. I aligned each AssemblyInfo.cs so comparison is easy. I placed comment markers for the common lines in the unique files and the unique lines in the common file.
Notes:
- I left a few attributes that are unused (e.g. Description) in each AssemblyInfo.cs as they should be unique despite them not being populated …
> Common assembly info

- NitroxModel/DataStructures/NitroxId.cs
- NitroxServer/GameLogic/EscapePodManager.cs
This patch makes the secondary systems and the radio of the escape pod repairable again.
The == operator doesn't seem to work for comparing the NitroxIds so I changed it to .Equals() to make the repairing work.
> Added "==" and "!=" operator to NitroxId. (Fixes repairability of escape pod)

- NitroxLauncher/App.xaml.cs
- NitroxServer/IpLogger.cs
Should reduce issues in help channel on discord down the line by running Nitrox Launcher from zip without extracting it first.
> Added error if Nitrox Launcher is started from temp directory

- NitroxModel/Discovery/GameInstallationFinder.cs
- NitroxModel/Discovery/InstallationFinders/EpicGamesInstallationFinder.cs
> Subnautica below zero is sometimes detected as the install path for classic Subnautia. Need to improve installation detection to exclude below zero. See the GameFinder classes in Nitrox
After our quick conversation on Discord, I keep going in trying to understand where the bug could came from. And for Epic Games it could exist one issue where the manifest file of subnautica zero is the first to be read then the Regex will catch it and our check will let Below Zero passing throught 👎 
**Old code :**
```
Match match = installLocationRegex.Match(fileText)
if (fileText.Contains("Subnautica") && match.Success) {
Log.Debug($"Found Subnautica install path in '{Path.GetFullPath(file)}'. Full pattern match: '{match.Value}'");
return Optional<string>.Of(match.Groups[1].Value);
}
```
> Quick Fix for Below Zero

- NitroxClient/GameLogic/InitialSync/PlayerInitialSyncProcessor.cs
Sets the players food and water when the player reconnects to the server
Fixes #978
> Reload of player food/water

- NitroxLauncher/MainWindow.xaml
- NitroxLauncher/MainWindow.xaml.cs
- NitroxLauncher/Patching/AppHelper.cs
We agreed on the fact that this textblock isn't really needy, moreover it's pushing the NitroxRelease Version out of the window
> Remove unwanted RunAsAdminMode in launcher

- NitroxClient/GameLogic/InitialSync/PlayerPositionInitialSyncProcessor.cs
Players that have been spawned inside a base were swimming and lacking oxygen. Upon exiting the base to get oxygen, the "entering animation" was played and they actually entered the base, instead of exiting. This was patched. Now, if you spawn inside a base, you have oxygen and on exit via a hatch, you actually exit the base.
> Fixed: No air if spawned inside base

- NitroxClient/MonoBehaviours/Gui/Chat/PlayerChatInputField.cs
- NitroxModel/Packets/ServerCommand.cs
- NitroxPatcher/Patches/Dynamic/DayNightCycle_OnConsoleCommand_day_Patch.cs
- NitroxPatcher/Patches/Dynamic/DayNightCycle_OnConsoleCommand_night_Patch.cs
- NitroxServer/Communication/Packets/Processors/ServerCommandProcessor.cs
- NitroxServer/ConsoleCommands/ChangeAdminPasswordCommand.cs
- NitroxServer/ConsoleCommands/ChangeServerPasswordCommand.cs
- NitroxServer/ConsoleCommands/DeopCommand.cs
- NitroxServer/ConsoleCommands/KickCommand.cs
- NitroxServer/ConsoleCommands/ListCommand.cs
- NitroxServer/ConsoleCommands/LoginCommand.cs
- NitroxServer/ConsoleCommands/OpCommand.cs
- NitroxServer/ConsoleCommands/Processor/ConsoleCommandProcessor.cs
- NitroxServer/ConsoleCommands/TimeCommand.cs
- NitroxServer/ConsoleCommands/WhisperCommand.cs
- NitroxServer/ServerAutoFacRegistrar.cs
- Fixed List Command in Console
- Fixed Kick Command causing server to crash
- Moved Args Parsing logic from Client to ConsoleCommandProcessor
- Removed duplicated string.Join & string.Split that made the arguments split and join several times
- Fixed Day/Night dynamic patches with new Time command
> Updated Args parsing logic for server

- NitroxModel/Discovery/GameInstallationFinder.cs
- NitroxModel/Discovery/InstallationFinders/GameInCurrentDirectoryFinder.cs
- NitroxModel/NitroxModel.csproj
This caused the logs to be written to another game install directory depending on the order of the game install finders.
> Fixed game finder not checking current directory

- NitroxModel/DataStructures/Optional.cs
- NitroxPatcher/Main.cs
- NitroxTest/Model/OptionalTest.cs
NitroxPatcher now adds a new HasValue check at runtime for types of UnityEngine.Object to check if the object is alive before returning true.
Every time a new type is given to `Optional<TheType>` then it'll loop through the registered global conditions for HasValue and fetch all conditions that are assignable to the given type. This means that `Optional<GameObject>` will also have (at least) the checks that `Optional<UnityEngine.Object>` has.
Atm it won't refetch and cache the hasvalue conditions for a type if they change due to `Optional.AddHasValueCondition<T>()` calls. These calls should be done before the first Optional<T> is created where T is a type assignable to any condition types. As done here: https://github.com/SubnauticaNitrox/Nitrox/pull/1086/files#diff-4e5e5240065741957a35125 …
> Added UnityEngine.Object alive check to Optional indirectly

- NitroxClient/GameLogic/NitroxConsole.cs
- NitroxClient/GameLogic/Vehicles.cs
- NitroxModel-Subnautica/DataStructures/GameLogic/CyclopsModel.cs
- NitroxModel-Subnautica/DataStructures/GameLogic/ExosuitModel.cs
- NitroxModel-Subnautica/DataStructures/GameLogic/SeamothModel.cs
- NitroxModel-Subnautica/Helper/VehicleConstructionFactory.cs
- NitroxModel-Subnautica/Helper/VehicleHelper.cs
- NitroxModel-Subnautica/Helper/VehicleModelFactory.cs
- NitroxModel-Subnautica/NitroxModel-Subnautica.csproj
- NitroxModel/DataStructures/GameLogic/VehicleModel.cs
- NitroxModel/DataStructures/GameLogic/VehicleMovementData.cs
- NitroxModel/Packets/ConstructorBeginCrafting.cs
- NitroxServer/Communication/Packets/Processors/VehicleColorChangeProcessor.cs
- NitroxServer/ConsoleCommands/BackCommand.cs
- NitroxServer/GameLogic/Vehicles/VehicleManager.cs
- Fix a bug where _ExoSuit_ colors where not initialized causing **NRE** at initial syncing and also when trying to change colors inside a moonpool terminal _(Because exosuits SubName colors aren't defined yet for odd reasons)_
- Fix a bug where _Exosuit_ colors wheren't updated in live for players
- Removed Colours field for VehicleModel (Just redundant informations since colors are computed by Subnautica throught HSB field)
> VehicleColor logic update

- NitroxClient/GameLogic/InitialSync/CyclopsInitialAsyncProcessor.cs
Fix a bug where we were still listening to OnVehicleCreated event forever if we had 0 cyclops to spawn
> CyclopsInitialSync fix (again)

- Nitrox.Bootloader/Main.cs
- NitroxLauncher/LauncherLogic.cs
- Added arg option to Subnautica.exe for providing launcher path so multiple instances can be started. (previously impossible due to removing the appdata file that has the launcher path on every start).
`"F:\Steam Games\steamapps\common\Subnautica\Subnautica.exe" -nitrox "E:\Programming\GitHub\Nitrox\NitroxLauncher\bin\Debug"`
> Fixed multi instance not working

- NitroxClient/NitroxClient.csproj
- NitroxClient/packages.config
- NitroxModel-Subnautica/NitroxModel-Subnautica.csproj
- NitroxModel-Subnautica/packages.config
- NitroxModel/NitroxModel.csproj
- NitroxModel/packages.config
- NitroxPatcher/NitroxPatcher.csproj
- NitroxPatcher/packages.config
- NitroxServer-Subnautica/NitroxServer-Subnautica.csproj
- NitroxServer-Subnautica/packages.config
- NitroxServer/NitroxServer.csproj
- NitroxServer/packages.config
- NitroxTest/NitroxTest.csproj
- NitroxTest/packages.config
Since we're not using xml/json custom config for Autofac, this nugget is not necessary
[Autofac doc](https://autofaccn.readthedocs.io/en/latest/configuration/xml.html#configuring-with-application-configuration-legacy-pre-4-0)
> Dropping Autofac.Configuration dependency

- NitroxClient/Communication/NetworkingLayer/LiteNetLib/LiteNetLibClient.cs
- NitroxServer/Communication/NetworkingLayer/LiteNetLib/LiteNetLibServer.cs
Elevated timeout-threshold to 5 min (in `DEBUG` build) to debug server code "live" without disconnecting.
> Added high timeout-threshold for debug purpose.

- NitroxClient/GameLogic/InitialSync/PlayerInitialSyncProcessor.cs
- NitroxModel/Server/ServerConfig.cs
- NitroxServer-Subnautica/App.config
Set the default infection level to 0.1f to match the value set by vanilla game on first launch.
End result:
New players now start the game as NOT Infected but also Not Cured as in the vanilla game.
> Initial Infection not set to Cured by default.

- NitroxServer-Subnautica/AppMutex.cs
- NitroxServer-Subnautica/NitroxServer-Subnautica.csproj
- NitroxServer-Subnautica/Program.cs
- NitroxServer/ConsoleCommands/Processor/ConsoleCommandProcessor.cs
- NitroxServer/ConsoleCommands/RestartCommand.cs
- NitroxServer/NitroxServer.csproj
- NitroxServer/Server.cs
- Fixed issue where server config changes made in the properties file were overwritten on server exit.
- Added port already in use checks that waits 30 seconds for the port to be available in case users have multiple servers running that try to run on the same port.
Due to the port check I needed to add a mutex so that multiple servers won't race the port and throw exceptions in LiteNetLib.
The mutex needs to run on the same thread so I started a new thread that is purely for that to avoid issues with `async` & `await` throwing exceptions to due context switching when accessing the mutex.
> Added server restart command and port binding checks

- NitroxModel/Logger/ColoredConsoleSink.cs
- NitroxModel/Logger/Log.cs
- NitroxModel/Logger/MessageSink.cs
- NitroxModel/NitroxModel.csproj
- NitroxModel/packages.config
- NitroxPatcher/Main.cs
- NitroxServer-Subnautica/Program.cs
- NitroxServer/Serialization/ServerProtoBufSerializer.cs
NLog rules and filters were too confusing to use practically for sensitive information logging.
TODO:
Fixes #1313
> Moved from NLog to Serilog

- NitroxPatcher/Patches/Persistent/ScreenshotManager_Initialise.Path.cs
Game saves screenshots to "screenshots" subdir. Can't easily fix to use uppercase S without using transpilers on all places that it is used.
> Moved screenshots to launcher directory

- NitroxModel/Logger/Log.cs
- NitroxPatcher/Main.cs
Disabled console logging for NitroxClient. Player.log will no longer contain Nitrox logs.
Fixes #1004
> Redirected unity logs to Nitrox Logs files

- NitroxModel/Logger/Log.cs
Previously one log file was shared across all programs but that made the log file harder to read.
> Changed log file names to include server, client or launcher

- NitroxModel/DataStructures/GameLogic/NitroxVector3.cs
- NitroxServer/Communication/NetworkingLayer/LiteNetLib/LiteNetLibConnection.cs
- NitroxServer/Communication/NetworkingLayer/LiteNetLib/LiteNetLibServer.cs
- NitroxServer/Communication/NetworkingLayer/NitroxServer.cs
- NitroxServer/GameLogic/ConnectionAssets.cs
- NitroxServer/GameLogic/PlayerManager.cs
Possibly fixes error "unauthenticated packet" occurring when calling `GetPlayer` and it cannot be found in the dictionary because it's reference equals.
> Added GetHashCode impl for connection obj

- NitroxModel-Subnautica/DataStructures/GameLogic/Buildings/Rotation/Metadata/AnchoredFaceRotationMetadata.cs
- NitroxModel-Subnautica/DataStructures/GameLogic/Buildings/Rotation/Metadata/BaseModuleRotationMetadata.cs
- NitroxModel-Subnautica/DataStructures/GameLogic/Buildings/Rotation/SubnauticaRotationMetadataFactory.cs
- NitroxModel/DataStructures/GameLogic/BasePiece.cs
- NitroxTest/Serialization/WorldPersistenceTest.cs
The reason behind this error:
Json needs (in our setup with protobuf and old json version from Oculus) a constructor with all fields/properties as parameters. Every parameter has to be the same type as the field/property. Any other constructor (like the parameter-less for protobuf) has to be `protected` or `private`. The Server can reference the new json version and is free from those restrictions because the fields/properties can be flagged with the json attribute (like protobuf with `ProtoMember`).
> Fixed serialization error with BasePiece and JSON

- NitroxPatcher/Patches/Persistent/Language_LoadLanguageFile_Patch.cs
This commit aims to fix blank menu in Subnautica
> Fixed loading of missing translation

- NitroxClient/GameLogic/EquipmentSlots.cs
- NitroxModel/Packets/ModuleAdded.cs
- NitroxModel/Packets/ModuleRemoved.cs
- NitroxServer/Communication/Packets/Processors/ModuleAddedProcessor.cs
- NitroxServer/Communication/Packets/Processors/ModuleRemovedProcessor.cs
- NitroxServer/Communication/Packets/Processors/PlayerJoiningMultiplayerSessionProcessor.cs
- NitroxServer/GameLogic/Items/InventoryData.cs
- NitroxServer/GameLogic/Items/InventoryManager.cs
- NitroxServer/Serialization/World/PersistedWorldData.cs
- NitroxServer/Serialization/World/WorldPersistence.cs
- NitroxTest/Serialization/WorldPersistenceTest.cs
Partly fixez #1406
Moves module tracking to global level so all players sync the same modules
Hopefully this will also help reduce the depth explosion issues people were having.
In theory I believe that a player module should never be added as they are tracked as PlayerEquipment but I thought I would leave it in just in case I had missed some edge case during testing, happy to remove if others believe this is also the case.
> Moved global modules to sync for all players

- NitroxClient/GameLogic/PlayerManager.cs
As you can see, the `DiscordRPController.Main.UpdatePlayerCount(GetTotalPlayerCount());` used to be called before the new Player is added to playersById, meaning that DiscordRP doesn't count the new player.
> Fixed a little issue with the DiscordRP player count

- NitroxClient/Communication/Packets/Processors/PlayerTeleportedProcessor.cs
- NitroxClient/GameLogic/InitialSync/PlayerPositionInitialSyncProcessor.cs
- NitroxClient/MonoBehaviours/NitroxEntity.cs
- NitroxModel/Packets/PlayerTeleported.cs
- NitroxServer/Communication/Packets/Processors/DefaultServerPacketProcessor.cs
- NitroxServer/Communication/Packets/Processors/PlayerDeathEventProcessor.cs
- NitroxServer/ConsoleCommands/BackCommand.cs
- NitroxServer/ConsoleCommands/TeleportCommand.cs
- NitroxServer/ConsoleCommands/WarpCommand.cs
- NitroxServer/Player.cs
Fixes #1414
- Fixed `warp`-command when destination player is inside cyclops 
- Added lastSubRootID for `back`-command
- Removed FMOD debug logging on server
> Fixed warp command when inside cyclops

- NitroxPatcher/Patches/Dynamic/EnergyMixin_ModifyCharge_Patch.cs
This is a fix for the bug that a Prawn Suit that is not fully charged is docked into the cyclops it would drain all power from the cyclops trying to charge itself but never getting any power.
The bug is also mentioned in this issue: #1359 
It did happen because the patched ModifyCharge method checked if the modification did a change to a different natural number before sending a sync packet. The problem was that this check did not compare the old charge with the new charge value but the new charge value with a value applying the modification again.
The Prawn Suit was draining 1 energy per second (normal power cells) and distribute it to it's 2 power cells. Each got 0.5 energy. The patched method now checked newCharge against newCharge + 0.5 and detected a natural number change although no …
> Fixed non fully charged vehicle in cyclops bay would drain all energy without getting charged

- NitroxServer-Subnautica/Program.cs
Might fix #1505
Nitrox used to bind a socket to the port (usually 11000) to test if it is available.
But apparently on some systems it will take too long to unbind the socket and will lead to error when server starts (see linked issue).
So the "fix" is to iterate the network API for all ports currently waiting for incoming packets instead. If one is 11000 (or the user defined port) it waits for it to become available with a timeout of 30 seconds.
- Verify server can start normally.
- Verify server waits for port when another server with the same port is already running.
> Changed port availability check to not bind to UDP port itself

- NitroxPatcher/Patches/Dynamic/QuickSlots_SelectInternal_Patch.cs
Code did null check but postfix runs always. So it also runs if item is null, hence the NRE spam in logs.
> Added nullchecks to quickslots postfix

- Directory.Build.props
- Nitrox.Bootloader/Nitrox.Bootloader.csproj
- NitroxClient/NitroxClient.csproj
- NitroxLauncher/NitroxLauncher.csproj
- NitroxModel-Subnautica/NitroxModel-Subnautica.csproj
- NitroxModel/NitroxModel.csproj
- NitroxPatcher/NitroxPatcher.csproj
- NitroxServer-Subnautica/NitroxServer-Subnautica.csproj
- NitroxServer/NitroxServer.csproj
**Before**
```
System.Exception: Oh no!
at NitroxLauncher.LauncherLogic.<StartSingleplayerAsync>d__34.MoveNext() in E:\Projects\GitHub\Nitrox\NitroxLauncher\LauncherLogic.cs:line 183
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at NitroxLauncher.Pages.LaunchGamePage.<SinglePlayerButton_Click>d__2.MoveNext() in E:\Projects\GitHub\Nitrox\NitroxLauncher\Pages\LaunchGamePage.xaml.cs:line 24
```
**After**
```
System.Exception: Oh no!
at NitroxLauncher.LauncherLogic.<StartSingleplayerAsync>d__34.MoveNext() in NitroxLauncher\LauncherLogic.cs:line 183
--- End of stack trace from previous …
```
> Changed PDB source paths to be relative to project

- NitroxLauncher/Patching/NitroxEntryPatch.cs
- NitroxLauncher/Patching/QModHelper.cs
- NitroxModel/OS/FileSystem.cs
On `MoveFile` win32 function:
> The MoveFile function will move (rename) either a file or a directory (including its children) either in the same directory or across directories. The one caveat is that the MoveFile function will fail on directory moves when the destination is on a different volume.
https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-movefile
This function is used by `File.Move` in .NET Framework 4.8 or lower.
Unfortunately we can't use .NET Core or .NET 5+ which use a different function that can copy files/directories between drives:
https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-movefileexw
> Changed File.Move usages to FileSystem.ReplaceFile because it can move files/directories between drives

- NitroxServer/Serialization/World/WorldPersistence.cs
The seed from the server config file wasn't actually being used anywhere, so I implemented it into the world generation for production environments.
> Fixed seed loading from config file in production environments

- NitroxLauncher/LauncherLogic.cs
- NitroxLauncher/MainWindow.xaml.cs
- NitroxModel/OS/FileSystem.cs
- NitroxModel/OS/MacOS/MacFileSystem.cs
- NitroxModel/OS/Unix/UnixFileSystem.cs
- NitroxModel/OS/Windows/WinFileSystem.cs
If user restarts as admin then Nitrox Launcher will add file permissions where needed.
Fixes #1559
> Added error when Nitrox is not able to write/read files

- NitroxClient/GameLogic/InitialSync/PdaInitialSyncProcessor.cs
I sometimes was getting Null ref exceptions during load when reaching this point which would cause the whole loading to stop forever.  This fixes them and allowed me to load into the server.
implement null checks in PDA Initial Sync
> PDA Initial Sync NullRef Checks.

- NitroxLauncher/NitroxLauncher.csproj
- NitroxPatcher/NitroxPatcher.csproj
- NitroxPatcher/Patches/Dynamic/BaseAddBulkheadGhost_UpdatePlacement_Patch.cs
- NitroxPatcher/Patches/Dynamic/BaseAddModuleGhost_UpdatePlacement_Patch.cs
- NitroxPatcher/Patches/Dynamic/Constructable_Construct_Patch.cs
- NitroxPatcher/Patches/Dynamic/Creature_ChooseBestAction_Patch.cs
- NitroxPatcher/Patches/Dynamic/CyclopsExternalDamageManager_CreatePoint_Patch.cs
- NitroxPatcher/Patches/Dynamic/CyclopsLightingPanel_ToggleFloodlights_Patch.cs
- NitroxPatcher/Patches/Dynamic/CyclopsLightingPanel_ToggleInternalLighting_Patch.cs
- NitroxPatcher/Patches/Dynamic/CyclopsMotorModeButton_OnClick_Patch.cs
- NitroxPatcher/Patches/Dynamic/ExosuitGrapplingArm_OnHit_Patch.cs
- NitroxPatcher/Patches/Dynamic/FMODUWE_PlayOneShotImpl_Patch.cs
- NitroxPatcher/Patches/Dynamic/FMOD_CustomEmitter_OnPlay_Patch.cs
- NitroxPatcher/Patches/Dynamic/FMOD_CustomLoopingEmitter_OnPlay_Patch.cs
- NitroxPatcher/Patches/Dynamic/FMOD_CustomLoopingEmitter_PlayStopSound_Patch.cs
- NitroxPatcher/Patches/Dynamic/FMOD_StudioEventEmitter_PlayUI_Patch.cs
- NitroxPatcher/Patches/Dynamic/FMOD_StudioEventEmitter_Stop_Patch.cs
- NitroxPatcher/Patches/Dynamic/LiveMixin_AddHealth_Patch.cs
- NitroxPatcher/Patches/Dynamic/LiveMixin_TakeDamage_Patch.cs
- NitroxPatcher/Patches/Dynamic/QuickSlots_SelectInternal_Patch.cs
- NitroxPatcher/Patches/Dynamic/Rocket_CallElevator_Patch.cs
- NitroxPatcher/Patches/Dynamic/Rocket_ElevatorControlButtonActivate_Patch.cs
- NitroxPatcher/Patches/Dynamic/SeaMoth_OnUpgradeModuleUse_Patch.cs
- NitroxPatcher/Patches/Dynamic/SubFire_CreateFire_Patch.cs
- NitroxPatcher/Patches/Dynamic/ToggleLights_SetLightsActive_Patch.cs
- NitroxPatcher/Patches/Dynamic/Utils_PlayFMODAsset_Patch.cs
- NitroxPatcher/Patches/Dynamic/VehicleDockingBay_OnTriggerEnter.cs
- NitroxPatcher/Patches/Dynamic/Welder_Weld_Patch.cs
- NitroxPatcher/Patches/NitroxPatch.cs
- NitroxTest/NitroxTest.csproj
Changes out Harmony2 for HarmonyX to be more compatible with QModManager in the future.
https://github.com/BepInEx/HarmonyX/wiki
info on the new patch type 
https://github.com/BepInEx/HarmonyX/wiki/ILManipulators
Info on some operational differences/improvements 
https://github.com/BepInEx/HarmonyX/wiki/Difference-between-Harmony-and-HarmonyX
> Convert to HarmonyX

- NitroxClient/MonoBehaviours/Gui/MainMenu/LoadingScreenVersionText.cs
Simple change that only fades out the Nitrox version on screen text but only when in VR as it is very disorienting in VR.
> Fades out disorienting Nitrox Alpha Version text when in VR

- NitroxPatcher/Patches/Dynamic/BuilderTool_HandleInput_Patch.cs
DeconstructionBegin needs a NitroxId not a gameobject. 
Every time I would try to deconstruct something it would throw an exception as this method was being provided with the wrong type.
> BuilderTool_HandleInput_Patch Transpiler fix

- NitroxPatcher/Patches/Dynamic/Seamoth_SubConstructionComplete_Patch.cs
Switched to Seamoth.toggleLights shortcut for locating and validated not null before setting value.
> Fix for ToggleLights not found on seamoth construction complete

- NitroxClient/GameLogic/Bases/Metadata/SignMetadataProcessor.cs
Small Lockers with a name stop the world from loading as the sign component is not active when metadata is being restored causing the getcomponentinchildren to fail to find it causing a nullref which breaks the initial loader.
> Sign metadata processor null ref fix

- NitroxServer-Subnautica/Program.cs
- NitroxServer/GameLogic/Entities/EntityManager.cs
- NitroxServer/GameLogic/Entities/Spawning/BatchEntitySpawner.cs
- NitroxServer/GameLogic/Entities/Spawning/IEntitySpawner.cs
- NitroxServer/Serialization/ServerConfig.cs
- NitroxServer/Server.cs
https://github.com/SubnauticaNitrox/Nitrox/issues/1109
Add functionality for the server to Cache all entity batches on the NEXT server start. This will loop through all possible batches and try to load them into the entity cache. 
Gated behind a new configuration option:
`# Set to true to Cache entities for the whole map on next run. `
`# WARNING! Will make server load take longer on the cache run but players will gain a performance boost when entering new areas.`
`CreateFullEntityCache=True`
> Load Entity Batches Up-Front and Cache

- Nitrox.Test/Server/GameLogic/EventTriggererTest.cs
- NitroxClient/Communication/Packets/Processors/ScheduleProcessor.cs
- NitroxClient/Communication/Packets/Processors/StoryEventHandler.cs
- NitroxClient/GameLogic/InitialSync/StoryGoalInitialSyncProcessor.cs
- NitroxModel-Subnautica/DataStructures/DataExtensions.cs
- NitroxModel/DataStructures/GameLogic/NitroxScheduledGoal.cs
- NitroxModel/Packets/StoryEventSend.cs
- NitroxPatcher/Patches/Dynamic/StoryGoalScheduler_Schedule_Patch.cs
- NitroxPatcher/Patches/Dynamic/StoryGoal_Execute_Patch.cs
- NitroxServer/Communication/Packets/Processors/PlayerJoiningMultiplayerSessionProcessor.cs
- NitroxServer/Communication/Packets/Processors/ScheduleProcessor.cs
- NitroxServer/GameLogic/EventTriggerer.cs
- NitroxServer/GameLogic/ScheduleKeeper.cs
- NitroxServer/GameLogic/StoryTimingData.cs
- NitroxServer/Server.cs
This will fix a bug that makes the radio play automatically and some changes
> Fix the radio changes to make it actually work

- Nitrox.Test/Patcher/Patches/CyclopsSonarButton_Update_PatchTest.cs
- NitroxClient/Communication/Packets/Processors/CyclopsChangeEngineModeProcessor.cs
- NitroxClient/Communication/Packets/Processors/CyclopsChangeSonarModeProcessor.cs
- NitroxClient/Communication/Packets/Processors/CyclopsToggleEngineStateProcessor.cs
- NitroxClient/Communication/Packets/Processors/VehicleColorChangeProcessor.cs
- NitroxClient/GameLogic/Cyclops.cs
- NitroxClient/MonoBehaviours/PlayerMovement.cs
- NitroxModel/DataStructures/GameLogic/VehicleMovementData.cs
- NitroxPatcher/Patches/Dynamic/CyclopsEngineChangeState_OnClick_Patch.cs
- NitroxPatcher/Patches/Dynamic/CyclopsHelmHUDManager_Start_Patch.cs
- NitroxPatcher/Patches/Dynamic/CyclopsHelmHUDManager_StopPiloting_Patch.cs
- NitroxPatcher/Patches/Dynamic/CyclopsMotorModeButton_OnClick_Patch.cs
- NitroxPatcher/Patches/Dynamic/CyclopsMotorMode_RestoreEngineState_Patch.cs
- NitroxPatcher/Patches/Dynamic/CyclopsSonarButton_OnClick_Patch.cs
- NitroxPatcher/Patches/Dynamic/CyclopsSonarButton_SonarPing_Patch.cs
- NitroxPatcher/Patches/Dynamic/CyclopsSonarButton_Update_Patch.cs
- NitroxServer-Subnautica/Program.cs
- NitroxServer/Communication/Packets/Processors/VehicleMovementPacketProcessor.cs
- NitroxServer/Server.cs
This PR will try to fix the existing bugs and maybe add some things that weren't synced yet
> Cyclops sync fix and improvements

- NitroxModel/Serialization/NitroxConfig.cs
Resolves issue with how we write new lines to file causing an erroneous ue line being listed at the end. This also resolves any future issues with shorter lines being added before longer causing erroneous lines to be created.
> Changed serialize file access type to truncate file before write

- NitroxServer/Serialization/ServerConfig.cs
I think this has been tested enough now to prove its stable going forward. This will help with issues people may have through allowing inspection of save files and with upgrading saves without having to switch serializer first.
I question if we want to remove the protobuf serializer completly as we wont use it?
> Changed default server serializer to json from protobuf

- NitroxModel/NitroxModel.csproj
Fixed the bug where we couldn't build in release mode due to this missing reference 
```cs
#if RELEASE
if (ip == null)
{
Regex regex = new(@"(?:[0-2]??[0-9]{1,2}\.){3}[0-2]??[0-9]+", RegexOptions.Compiled);
string[] sites =
{
"https://ipv4.icanhazip.com/",
"https://checkip.amazonaws.com/",
"https://api.ipify.org/",
"https://api4.my-ip.io/ip",
"https://ifconfig.me/",
"https://showmyip.com/",
};
// Missing type HERE
using HttpClient client = new();
```
> Added reference to System.Net.Http

- NitroxPatcher/Patches/Persistent/MonitorLauncher_Awake_Patch.cs
`MonitorLauncher` is a memory debug and warning utility for UWE. For some reason it fails at each game start so this pr prevents it's initialization.
> Remove error by MonitorLauncher

- NitroxClient/GameLogic/Vehicles.cs
- NitroxClient/MonoBehaviours/MultiplayerExosuit.cs
- NitroxClient/MonoBehaviours/MultiplayerSeaMoth.cs
- NitroxClient/MonoBehaviours/MultiplayerVehicleControl.cs
- NitroxPatcher/Patches/Dynamic/Vehicle_OnPilotModeEnd_Patch.cs
Title says it all, I hope it doesn't sound too much like a workaround (#1522)
To test, you need to force the issue, you can do this:
add the following code at line 353 (end of **OnVehiclePrefabLoaded**) in **Vehicles.cs**
```
switch (techType)
{
case TechType.Seamoth:
gameObject.EnsureComponent<MultiplayerSeaMoth>();
break;
case TechType.Exosuit:
gameObject.EnsureComponent<MultiplayerExosuit>();
break;
}
```
Then follow these instructions:
- Spawn an exosuit or a seamoth, leave the server then rejoin
- If you disable the fix (comment the "Exit()" in Vehicle_OnPilotModeEnd_Patch), you will see that there's the vehicle stuck bug
- Enable back the fix, then when you come back, if you join for the first time you will have the stuck bug for the vehicle, but as soon as you leave it and enter it …
> Fix the vehicle stuck on nothing bug

- NitroxClient/Properties/Resources.resx
Compilation will fail on a case-sensitive file system (e.g. Linux ext4).
> Correct soundsWhitelist path

- NitroxClient/MonoBehaviours/PlayerMovement.cs
Freecam does set the transform of the player to null and disable the camera gameobject causing various nullpointer inside our movement handler code.
```
[22:20:44.762] [ERR-UNITY] NullReferenceException: Object reference not set to an instance of an object
NitroxClient.MonoBehaviours.PlayerMovement.GetVehicleMovement () (at <76f1b38f81a64b09bc01bdb03a9086bb>:0)
NitroxClient.MonoBehaviours.PlayerMovement.Update () (at <76f1b38f81a64b09bc01bdb03a9086bb>:0)
```
> Fix for freecam nullpointer spam

- NitroxClient/MonoBehaviours/PlayerMovement.cs
The check for freecam detection may be not enough precise
> Fix cyclops not moving while controlling it through a camera

- NitroxModel/Discovery/GameInstallationFinder.cs
- NitroxModel/Discovery/InstallationFinders/EnvironmentGameFinder.cs
- NitroxServer/GameLogic/Items/InventoryManager.cs
**Background**
Right now we have no way to specify the install location explicitly. It would be useful to have a way to do this, as other ways can fail and the user can specify the path to the game himself. 
**Changes**
- Added `SUBNAUTICA_INSTALLATION_PATH`, which doesn't break the current functionality in any way.
**How to test**
- Change environment variable `SUBNAUTICA_INSTALLATION_PATH` (see how [here](https://www.architectryan.com/2018/08/31/how-to-change-environment-variables-on-windows-10/))
- Run server and check that path from environment variable catch correctly
If you have the game installed and one of the classes above has already found its way, you can test this change by moving that class up.
> Adding a way to specify the installation path through environment variables

- Nitrox.Test/Server/GameLogic/EventTriggererTest.cs
- NitroxClient/Communication/Packets/Processors/AuroraExplodeNowProcessor.cs
- NitroxClient/Communication/Packets/Processors/AuroraRestoreProcessor.cs
- NitroxModel/Packets/AuroraExplodeNow.cs
- NitroxModel/Packets/AuroraRestore.cs
- NitroxPatcher/Patches/Dynamic/CrashedShipExploder_OnConsoleCommand_explodeship_Patch.cs
- NitroxServer/ConsoleCommands/AuroraCommand.cs
- NitroxServer/GameLogic/EventTriggerer.cs
- NitroxServer/GameLogic/StoryTimingData.cs
- NitroxServer/Serialization/World/WorldPersistence.cs
- NitroxServer/Server.cs
These are the 4 commands:
- ``countdownship`` (will explode aurora as if we were just skipping to the last warning, which means we have the 20s of audio that come with aurora explosion in normal time)
- ``explodeship`` (will explode aurora instantly)
- ``restoreship`` (will restore the base state of aurora and restart all warning countdowns)
- ``explodeforce`` (only shows FX)
We sync all of them except explodeforce which is not worse syncing (tell me if you disagree), tho it is also deactivated.
Also, aurora command can't be executed from the server's console.
(Will show the number of the next warning to come)
> Synced commands concerning aurora

- NitroxServer/Communication/ConnectionState.cs
- NitroxServer/Communication/LiteNetLib/LiteNetLibConnection.cs
- NitroxServer/Communication/NitroxConnection.cs
- NitroxServer/GameLogic/InitialSyncTimerData.cs
- NitroxServer/GameLogic/PlayerManager.cs
A player could leave while in the JoinQueue and it would cause a null reference when trying to reserve that player later
> Fixes null ref in PlayerManager

- NitroxClient/GameLogic/RemotePlayer.cs
Some screenshots of the testing session in the thread ["light fix PR test session"](https://discord.com/channels/525437013403631617/975468417018658847)
(Tested with 3 players and seemed to work as expected)
How the fix works, we add a component named ``SkyApplier`` which goal is to adjust the lighting level of all the renderers inside a model depending on the lighting source.
Will fix #644
> Fix remote players' lighting

- Nitrox.Test/Server/GameLogic/EventTriggererTest.cs
- NitroxServer/GameLogic/EventTriggerer.cs
A small mistake of mine:
`AuroraExplosionTimeMs` is always supposed to be greater than `AuroraWarningTimeMs` but I was testing the opposite
> Aurora events calculations fix

- NitroxClient/Communication/Packets/Processors/VehicleDockingProcessor.cs
- NitroxClient/Communication/Packets/Processors/VehicleUndockingProcessor.cs
- NitroxClient/GameLogic/Bases/GeometryRespawnManager.cs
- NitroxClient/GameLogic/Bases/Spawning/BasePiece/BaseMoonpoolSpawnProcessor.cs
- NitroxClient/GameLogic/Bases/Spawning/BasePiece/BasePieceSpawnProcessor.cs
- NitroxClient/GameLogic/Cyclops.cs
- NitroxClient/GameLogic/RemotePlayer.cs
- NitroxClient/GameLogic/Vehicles.cs
- NitroxPatcher/Patches/Dynamic/VehicleDockingBay_OnTriggerEnter.cs
- NitroxPatcher/Patches/Dynamic/VehicleDockingBay_OnUndockingComplete_Patch.cs
There was an error about detecting properly which was the moonpool parent of the VehicleDockingBay
Would fix #1745, #1398 
EDIT: now, each time we rebuild geometry, we also reapply the spawn processor because the gameobjects children were kind of "resetted"
> Fix moonpools undocking not working

- NitroxClient/GameLogic/RemotePlayer.cs
Little reminder that lifepods aren't considered as subroots
> Fix player lighting when entering lifepods

- Directory.Build.props
- NitroxModel/NitroxModel.csproj
Might be that to fix both these issues we need to move this analyzer to another repo and deploy on NuGet. But I wonder if this will make it harder to iterate while developing the analyzers.
Feature request for allowing project referenced analyzers to work: https://github.com/dotnet/roslyn/issues/18093
> Added first .NET analyzer for validating packet deserialization

- NitroxClient/ClientAutoFacRegistrar.cs
- NitroxClient/GameLogic/LocalPlayer.cs
- NitroxClient/GameLogic/PlayerLogic/PlayerModel/ColorSwap/ColorSwapAsyncOperation.cs
- NitroxClient/GameLogic/PlayerLogic/PlayerModel/ColorSwap/HsvSwapper.cs
- NitroxClient/GameLogic/PlayerLogic/PlayerModel/ColorSwap/RebreatherColorSwapManager.cs
- NitroxClient/GameLogic/PlayerLogic/PlayerModel/PlayerModelManager.cs
- NitroxClient/GameLogic/PlayerManager.cs
- NitroxClient/MonoBehaviours/Multiplayer.cs
- NitroxClient/MonoBehaviours/NitroxBootstrapper.cs
- NitroxModel/MultiplayerSession/PlayerSettings.cs
Fix an issue where joining players would have the same color as you while their ping has the correct color.
This is achieved by early init of the body prototype before the first color swapping operation. The body prototype shouldn't be colored in the first place since color swapping operations is mapped on the original texture pixels (which are orange)
PS: Might be worth to investigate in a cache for SwapColorOperation since it's the exact same process everytime
> Fix player color for different players

- Nitrox.Test/Serialization/WorldPersistenceTest.cs
- NitroxClient/Communication/Packets/Processors/DeconstructionCompletedProcessor.cs
- NitroxClient/GameLogic/Bases/GeometryRespawnManager.cs
- NitroxClient/GameLogic/Bases/Spawning/BasePiece/BaseBioReactorSpawnProcessor.cs
- NitroxClient/GameLogic/Bases/Spawning/BasePiece/BaseLadderSpawnProcessor.cs
- NitroxClient/GameLogic/Bases/Spawning/BasePiece/BaseMoonpoolSpawnProcessor.cs
- NitroxClient/GameLogic/Bases/Spawning/BasePiece/BasePieceSpawnPrioritizer.cs
- NitroxClient/GameLogic/Bases/Spawning/BasePiece/BasePieceSpawnProcessor.cs
- NitroxClient/GameLogic/Bases/Spawning/BasePiece/BaseWaterParkProcessor.cs
- NitroxClient/GameLogic/Bases/Spawning/BasePiece/MapRoomSpawnProcessor.cs
- NitroxClient/GameLogic/Building.cs
- NitroxClient/MonoBehaviours/Overrides/MultiplayerBuilder.cs
- NitroxClient/MonoBehaviours/ThrottledBuilder.cs
- NitroxModel-Subnautica/DataStructures/GameLogic/Buildings/Rotation/Metadata/AnchoredFaceBuilderMetadata.cs
- NitroxModel-Subnautica/DataStructures/GameLogic/Buildings/Rotation/SubnauticaRotationMetadataFactory.cs
- NitroxModel/Packets/DeconstructionCompleted.cs
- NitroxPatcher/Patches/Dynamic/Base_CopyFrom_Patch.cs
- NitroxPatcher/Patches/Dynamic/Base_SetFace_Patch.cs
- NitroxServer/Communication/Packets/Processors/DeconstructionCompletedPacketProcessor.cs
- NitroxServer/GameLogic/Bases/BaseManager.cs
- ~~Repair an instance of ladders not being built on reconnection only~~
**This may need more testing.**
Concerning the `AreSameTechType()` part, I've tested manually for all the pieces.
Also I've made a messy reordering function in `BasePieceSpawnPrioritizer.cs` because I didn't know how to make it, can someone indicate me a better way of doing this please ?
The ladders issue will remain since it can happen and not happen in the same conditions, I won't look more into it
> Fix many building bugs

- Nitrox.Test/Patcher/Patches/Dynamic/Inventory_LoseItems_PatchTest.cs
- NitroxPatcher/Patches/Dynamic/Inventory_LoseItems_Patch.cs
- NitroxPatcher/Patches/Dynamic/Pickupable_Drop_Patch.cs
What the fix does is we delete the dropped items after they have sent a packet to the server.
Consequently, when we'll get back to the death place, we'll ONLY get the loaded items and not those that were left there by the drop instruction.
Fixes #1841 
To test this:
- just take two players (in survival possibly) and go a bit further than the lifepod.
- Clear your inventory on both players (so that you don't have overflowing stuff in your hands).
- Have one player gather some ores and take a screenshot of the inventory's contents when you're done
- Use /kill with the player that has the ores, WHILE the second player is watching so that he can acknowledge that the ores are dropped when he dies.
- Use /back with the player who died and notice that the ores are not duplicated.
> NB: We use …
> Fix duplicated items on death

- Nitrox.Assets.Subnautica/LanguageFiles/en.json
- NitroxClient/Communication/Packets/Processors/AnimationProcessor.cs
- NitroxClient/GameLogic/InitialSync/RemotePlayerInitialSyncProcessor.cs
- NitroxClient/GameLogic/ItemContainers.cs
- NitroxClient/GameLogic/PlayerLogic/RemotePlayerIdentifier.cs
- NitroxClient/GameLogic/RemotePlayer.cs
- NitroxPatcher/Patches/Dynamic/Base_OnPreDestroy_Patch.cs
- NitroxPatcher/Patches/Dynamic/Utils_GetEntityRoot_Patch.cs
> When the RemotePlayer object is destroyed, all of its inventory is destroyed too and will send parasite packets with fake informations (like item removal)
> Fix some occurrences of player inventory clear

- Directory.Build.props
- NitroxServer/Serialization/World/WorldManager.cs
- Bumped version to v1.7.0.0
- Bumped minimum save file version allowed to v1.7.0.0 (since saves from v1.6.0.1 and under are not supported anymore)
> Bump assembly version to v1.7.0.0

- Directory.Build.props
Steps to test (at least when using Rider IDE):
1. `git clean -xdf`
2. `dotnet restore`: throws error that says to run `Nitrox.BuildTool`
3. Try to run `Nitrox.BuildTool`: throws errors that it's missing nuget packages
4. Back to step 2..
> Removed PrepareForModding target from InitialTargets attr so that restore can happen

- NitroxPatcher/Patches/Dynamic/uGUI_Pings_OnLateUpdate_Patch.cs
Fixes compile issue with experimental changes
> Changed OnLateUpdate to UpdatePings

- NitroxClient/Communication/Packets/Processors/CellEntitiesProcessor.cs
- NitroxClient/GameLogic/Entities.cs
- NitroxClient/GameLogic/HUD/Components/uGUI_PlayerPingEntry.cs
- NitroxClient/GameLogic/HUD/PdaTabs/uGUI_PlayerListTab.cs
- NitroxClient/GameLogic/HUD/PlayerListTab.cs
- NitroxClient/GameLogic/Helper/InventoryContainerHelper.cs
- NitroxClient/GameLogic/PlayerLogic/PlayerModel/PlayerModelManager.cs
- NitroxClient/GameLogic/Spawning/DefaultEntitySpawner.cs
- NitroxClient/MonoBehaviours/Gui/HUD/RemotePlayerVitals.cs
- NitroxClient/MonoBehaviours/Gui/MainMenu/JoinServer.cs
- NitroxClient/MonoBehaviours/Multiplayer.cs
- NitroxModel/Logger/Log.cs
- NitroxPatcher/Patches/Dynamic/SpawnEscapePodSupplies_OnNewBorn_Patch.cs
Entities are mostly spawning - still some slowness in starting chunks though.  It also looks like simulation ownership system is working fine.  This PR does have some benign unauthenticated packets due to moving the dynamic patching location - we can work through these with suppression when we get to them. 
* Changed dynamic patching hook to be earlier on.  This allows patches that require early initialization to function (such as uGUI_PDA)
* Fixed several bugs in entity spawning async transformation
* Fixes to allow users to spawn alongside their remote vitals
* Prevented PDA from erroring out initial syncs with multiple players
* Added a new patch to prevent escape pod supplies from spawning
* Small tweak to logger to only log a warning instead of throwing when attempting to …
> Several stabilization changes to get us closer to a playable build, including:

- NitroxClient/Communication/Packets/Processors/PlayerMovementProcessor.cs
- NitroxClient/Communication/Packets/Processors/VehicleDockingProcessor.cs
- NitroxClient/Communication/Packets/Processors/VehicleUndockingProcessor.cs
- NitroxClient/GameLogic/Bases/Spawning/BasePiece/BasePieceSpawnProcessor.cs
- NitroxClient/GameLogic/Cyclops.cs
- NitroxClient/GameLogic/InitialSync/PlayerPreferencesInitialSyncProcessor.cs
- NitroxClient/GameLogic/LocalPlayer.cs
- NitroxClient/GameLogic/MovementHelper.cs
- NitroxClient/GameLogic/RemotePlayer.cs
- NitroxClient/GameLogic/Terrain.cs
- NitroxClient/GameLogic/Vehicles.cs
- NitroxClient/MonoBehaviours/Discord/DiscordJoinRequestGui.cs
- NitroxClient/MonoBehaviours/Gui/Chat/PlayerChat.cs
- NitroxClient/MonoBehaviours/MultiplayerVehicleControl.cs
- NitroxClient/MonoBehaviours/PlayerMovementBroadcaster.cs
- NitroxClient/Unity/Helper/Yielders.cs
- NitroxPatcher/Patches/Dynamic/PDAScanner_Scan_Patch.cs
Nitrox uses a velocity-based system to update remote player locations.  This provides a fluid movement and doesn't incur large costs associated with setting the transform position over and over.  However, with the recent Subnautica update, it appears that we update the velocity too quickly.  Movement updates don't appear to apply velocity for multiple packets then cause the player to over correct.  It is likely that Nitrox is applying velocity updates too frequently for the physics engine to react (0.05s). 
In this PR, I've updated the frequency of movement packets to 0.12s.  This caused normal movement behavior; however, not very smooth.  To counteract this, I also enabled some interpolation to bring back the smoothness.  We can play with these a bit more; however, this configuration …
> Fix remote player stuttering/teleporting when standing still or moving.

- NitroxServer-Subnautica/Program.cs
- NitroxServer-Subnautica/Resources/Parsers/Abstract/AssetParser.cs
- NitroxServer-Subnautica/Resources/Parsers/Helper/AssetsBundleManager.cs
- NitroxServer-Subnautica/Resources/Parsers/Helper/ThreadSafeMonoCecilTempGenerator.cs
- NitroxServer-Subnautica/Resources/Parsers/PrefabPlaceholderGroupsParser.cs
- NitroxServer-Subnautica/Resources/Parsers/ThreadSafeMonoCecilTempGenerator.cs
- NitroxServer-Subnautica/Resources/ResourceAssetsParser.cs
Assemblies loaded by reference of the targeted asset assemblies can't be unloaded without changing AssetTools.NET code here. (We only have a reference to some of the assemblies, and can only dispose those):
https://github.com/nesrak1/AssetsTools.NET/blob/upd21-with-inst/AssetTools.NET/Extra/MonoDeserializer/MonoCecilTempGenerator.cs#L63-L69
**Preview of handles after full load of server**
> Fixed dispose of assemblies loaded via asset parsing on server

- Nitrox.Analyzers/Diagnostics/LocalizationAnalyzer.cs
- Nitrox.Analyzers/Extensions/DebugExtensions.cs
- Nitrox.Analyzers/Nitrox.Analyzers.csproj
- Nitrox.BuildTool/Program.cs
- Nitrox.BuildTool/Publicizer.cs
Used symbol lookup and compare in localization to make it match exactly the right type (`Language` in `Assembly-Csharp`). This change required upgrade to roslyn 4.2.0 for `Compilation.GetTypesByMetadataName` API.
Tested analyzers still work in VS and Rider when using latest versions of either.
See: https://learn.microsoft.com/en-us/visualstudio/extensibility/roslyn-version-support?view=vs-2022 for compatible IDEs with the roslyn nuget package.
> Upgraded analyzer package to align with modern C# SDK

- NitroxClient/MonoBehaviours/Multiplayer.cs
- NitroxModel/Core/NitroxServiceLocator.cs
- NitroxPatcher/Patches/NitroxPatch.cs
- NitroxServer/Communication/Packets/PacketHandler.cs
Performance difference can be seen here, where `.MakeGenericType(...)` lookups take ~0.2ms and cached lookups ~0.-0005 to ~0.001ms. A **~400x speedup** but only for the lookup part, not the processing itself.
This should reduce latency issues.
```log
[11:36:57.897] [DBG] Perf: Processor lookup took 0.2477ms
[11:37:38.220] [DBG] Perf: Processor lookup took 0.3134ms
[11:37:38.221] [DBG] Perf: Processor lookup took 0.2795ms
[11:37:38.237] [DBG] Perf: Processor lookup took 0.0077ms
[11:37:38.237] [DBG] Perf: Processor lookup took 0.0003ms
[11:37:38.246] [DBG] Perf: Processor lookup took 0.0005ms
[11:37:38.246] [DBG] Perf: Processor lookup took 0.0003ms
[11:37:38.295] [DBG] Perf: Processor lookup took 0.0006ms
[11:37:38.338] [DBG] Perf: Processor lookup took 0.4232ms
[11:37:38.812] [DBG] Perf: …
```
> Optimize packet handling in client and server by caching type to processor lookup

- NitroxModel/Helper/Reflect.cs
- NitroxPatcher/Patches/Dynamic/BaseAddBulkheadGhost_UpdatePlacement_Patch.cs
- NitroxPatcher/Patches/Dynamic/BaseAddModuleGhost_UpdatePlacement_Patch.cs
- NitroxPatcher/Patches/Dynamic/ExosuitClawArm_TryUse_Patch.cs
- NitroxPatcher/Patches/Persistent/Language_LoadLanguageFile_Patch.cs
Expressions can't create and capture variables. But they can refer to a preexisting variable.
> Fixed Reflect API for out parameters

- README.md
Wiki Link on our GitHub page was outdated. I updated it to the right link.
Now you get to the right page when clicking the wiki links in the github Readme.
> Readme wiki-link updated

- Nitrox.Test/Server/Serialization/WorldPersistenceTest.cs
- NitroxClient/GameLogic/Entities.cs
- NitroxClient/GameLogic/InitialSync/QuickSlotInitialSyncProcessor.cs
- NitroxClient/GameLogic/LocalPlayer.cs
- NitroxClient/GameLogic/Spawning/InventoryItemEntitySpawner.cs
- NitroxModel/Packets/InitialPlayerSync.cs
- NitroxModel/Packets/PlayerQuickSlotsBindingChanged.cs
- NitroxPatcher/Patches/Dynamic/QuickSlots_Bind_Patch.cs
- NitroxServer/Communication/Packets/Processors/PlayerJoiningMultiplayerSessionProcessor.cs
- NitroxServer/Communication/Packets/Processors/PlayerQuickSlotsBindingChangedProcessor.cs
- NitroxServer/GameLogic/PlayerManager.cs
- NitroxServer/GameLogic/Players/PersistedPlayerData.cs
- NitroxServer/Player.cs
This should be another new feature.  Nitrox existing code for recording quick slot bindings; however, these never got replayed during the initial sync.  Also, this existing code recorded UWE unique identifiers so needed some slight refactoring to use nitrox ids.
Example adding several duplicate items, setting them into quick slots 1/2 and 3/5, then reloading the server several times:
> Persisting and syncing quick bind slots

- NitroxClient/GameLogic/Entities.cs
- NitroxClient/GameLogic/Spawning/WorldEntities/PlaceholderGroupWorldEntitySpawner.cs
Subnautica spawns placeholder objects as siblings of placeholder groups.  Example taken from debugger in single player:
The Nitrox behavior was spawning these as direct children.  This behavior was resulting in two major issues:
1) The game wipes children of PrefabPlaceholderGroups at serialization time causing us to maintain custom logic to respawn the children after batch deserilization.  
2) Some child components rely on the unity messaging framework to communicate.  For example the `PrecursorKeyTerminal` needs to send a `ToggleDoor` message through the parent to `PrecursorDoor`.  This is not possible if the parenting is incorrect.  
This PR fixes instances of precursor objects not working, for example:
It also removes the custom batch deserialization code as it is no longer required.
> Fixed placeholder nesting causing batch issues and broken precursor objects.

- NitroxClient/GameLogic/Items.cs
- NitroxPatcher/Patches/Dynamic/IncubatorActivationTerminal_OnPlayerCinematicModeEnd_Patch.cs
- NitroxPatcher/Patches/Dynamic/Incubator_OnHatched_Patch.cs
- NitroxPatcher/Patches/Dynamic/PrecursorKeyTerminal_DestroyKey_Patch.cs
- NitroxPatcher/Patches/Dynamic/PrecursorTeleporterActivationTerminal_OnPlayerCinematicModeEnd_Patch.cs
- NitroxPatcher/Patches/Dynamic/Survival_Eat_Patch.cs
- NitroxPatcher/Patches/Dynamic/Survival_Use_Patch.cs
- NitroxServer/Communication/Packets/Processors/EntityDestroyedPacketProcessor.cs
- NitroxServer/GameLogic/Entities/WorldEntityManager.cs
Nitrox currently has several codepaths that don't report a destroyed entity.  I went through and plugged some of the major gaps. 
This PR also includes a minor bug fix to remove broadcasting on picked up items and a circular dependency between server classes.
> Added entity deletion accounting at several locations.

- NitroxClient/Communication/Packets/Processors/SimulationOwnershipChangeProcessor.cs
- NitroxClient/GameLogic/HUD/PdaTabs/uGUI_PlayerListTab.cs
- NitroxClient/GameLogic/PlayerLogic/PlayerModel/PlayerModelManager.cs
- NitroxClient/GameLogic/Spawning/WorldEntities/PlayerWorldEntitySpawner.cs
- NitroxClient/GameLogic/Spawning/WorldEntities/VehicleWorldEntitySpawner.cs
- NitroxClient/MonoBehaviours/Gui/InGame/Modal.cs
- NitroxPatcher/Patches/Dynamic/FreezeTime_Begin_Patch.cs
- NitroxServer/Communication/Packets/Processors/PlayerMovementProcessor.cs
1) Players not being able to enter a newly constructed cyclops due to missing cinematic controllers.
2) Player pings were not showing up due to inappropriate parenting of the remote player game object in addition to unnecessary offset on ping position.
3) The player entity was never having its position updated on the server side.  This makes some calculations incorrect (such as isSwimming).  Currently these positions are in two places, there is a todo item to consolidate.  
4) Fixed a long-standing record keeping bug with simulation lock type not stored on the client properly.  To my knowledge this has no effect as singular lock requests go through a different code path.  However, it was a land mine that should be fixed.  
5) Fixed multiple bugs causing player ping manager to not register …
> Adding fixes for multiple small bugs.

- NitroxClient/Debuggers/Drawer/UnityUI/RectTransformDrawer.cs
- NitroxClient/GameLogic/HUD/Components/uGUI_PlayerPingEntry.cs
- NitroxClient/GameLogic/HUD/PdaTabs/uGUI_PlayerListTab.cs
- NitroxClient/GameLogic/HUD/PlayerListTab.cs
- Player list is back to normal with colors and everything, also made the buttons position moving it simpler.
Position moving issue was caused by the game not having enough time to startup UI elements properly and therefore misplacing the newly created buttons. Making the Start method of ``uGUI_PlayerPingEntry`` an IEnumerator and waiting for one frame before moving the buttons fixes it.
- Added the AnchoredPosition field for RectTransform which is more relevant that global/local position.
> Fix Player list and add AnchoredPosition to RectTransform's debug

- NitroxClient/MonoBehaviours/MultiplayerCyclops.cs
- NitroxPatcher/Patches/Dynamic/Player_RequiresHighPrecisionPhysics_Patch.cs
- NitroxPatcher/Patches/Dynamic/VFXConstructing_WakeUpSubmarine_Patch.cs
This an experimental PR to see if we can reduce the poor cyclops experience.
I've included two potential fixes:
1) When riding as a passenger, the cyclops interpolation switches rapidly between none/Interpolate each frame.  The root cause is `Player.RequiresHighPrecisionPhysics()` going in and out of criteria every few frames.  The change here is to give a constant value of 'true' when another player is piloting the sub.
2) Even with the above fix the cyclops would stick on 'Interpolate'.  This results in poor visual performance over 'None' when surfacing or diving in the cyclops (and can also launch the player more often!). This was due to the `FreezeRigidbodyWhenFar` causing permanent interpolate when in range although `RequiresHighPrecisionPhysics` should have locked interpolate to …
> Reducing jitter and stuttering as a cyclops passenger.

- Directory.Build.props
- Nitrox.Test/Model/ExtensionsTests.cs
- Nitrox.Test/Patcher/Patches/Dynamic/DevConsole_Update_PatchTest.cs
- Nitrox.Test/Patcher/Patches/Dynamic/ItemsContainer_DestroyItem_PatchTest.cs
- NitroxClient/Properties/AssemblyInfo.cs
- NitroxModel/Properties/AssemblyInfo.cs
- NitroxPatcher/Patches/Dynamic/DevConsole_Update_Patch.cs
- NitroxPatcher/Patches/Dynamic/ItemsContainer_DestroyItem_Patch.cs
- NitroxPatcher/PatternMatching/InstructionPattern.cs
- NitroxPatcher/PatternMatching/OperandPattern.cs
- NitroxPatcher/Properties/AssemblyInfo.cs
- NitroxServer/Properties/AssemblyInfo.cs
Removed manual definitions of InternalsVisibleTo in each project.
We've been using the same namespace in Nitrox.Test as the code it tests but with [this attribute](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.internalsvisibletoattribute?view=net-8.0) that's not needed.
> Added InternalsVisibleTo for all Nitrox projects in Directory.Build.props

- Nitrox.Test/Client/Communication/DeferredPacketReceiverTest.cs
- NitroxClient/Communication/NetworkingLayer/LiteNetLib/LiteNetLibClient.cs
- NitroxClient/Communication/PacketReceiver.cs
- NitroxClient/Communication/Packets/Processors/EntityTransformUpdatesProcessor.cs
- NitroxClient/Debuggers/NetworkDebugger.cs
- NitroxClient/GameLogic/Entities.cs
- NitroxClient/MonoBehaviours/EntityPositionBroadcaster.cs
- NitroxClient/MonoBehaviours/RemotelyControlled.cs
- NitroxModel/Extensions.cs
- NitroxModel/Packets/EntityTransformUpdates.cs
- NitroxPatcher/Patches/Dynamic/SplineFollowing_GoTo_Patch.cs
Currently, Nitrox broadcasts every simulated entity's position every 0.25 seconds.  This gives the appearance of fish synchronization but causes significant load - especially for non-LAN players.
This PR changes the mechanics behind movement simulation for most entities.  Things that have a SwimBehavior or WalkBehavior (that internally use a SplineFollow) will broadcast changes only when their destination changes.  This provides more fluid behavior and significantly reduces packet volume.
One thing to note is that some entities will still need the previous behavior.  For example, dropping an item that floats down to the bottom.  In this case, we can look towards future optimizations to dedupe packets when little movement actually occurred or perform a similar custom spline behavior. …
> Optimized position broadcasting and more network debugger info.

- NitroxLauncher/MainWindow.xaml
- NitroxLauncher/MainWindow.xaml.cs
- NitroxModel/Platforms/OS/Windows/Internal/Win32Native.cs
- NitroxModel/Platforms/OS/Windows/WindowsApi.cs
While working on a side WPF project, I was trying to find out how to restore the default window animations when creating a custom window (i.e. setting `WindowStyle="None"` for the base window), and I came across [this stack overflow question](https://stackoverflow.com/questions/56175722/how-to-restore-the-default-show-close-animations-for-a-window-when-setting-windo) that had code that somehow worked, for the most part. I tried putting it into the Nitrox launcher code and it worked there as well, so I decided that it might be a nice addition to the launcher.
It was also not supposed to restore the opening and closing animations of the window (it didn't for my project or for the user in that post), but it somehow did for the Nitrox launcher. There is just one small issue where the closing …
> Restore Launcher Window Animations

- NitroxClient/MonoBehaviours/Gui/MainMenu/MainMenuMultiplayerPanel.cs
Should close #1995 by disabling button when showingAddServer enabled
Main method for disabling button is handled in OnGUI but utilises a flag to prevent multiple expensive ops per frame. should mean it should run the expensive ops on 1 frame, and never again until the state changes
This fix required both modifying a variable name and moving this gameobject var to an outer scope. I have ran basic tests throughout the menu and have not observed any issues with this whatsoever. but if there is something deep-rooted that this would affect, I can try and approach it from a different angle.
> Disable "Add Server" button when add server window overlay enabled

- NitroxClient/MonoBehaviours/Gui/Input/KeyBindingManager.cs
- NitroxClient/MonoBehaviours/Gui/Input/KeyBindings/KeyBinding.cs
- NitroxClient/Serialization/ClientConfig.cs
- NitroxModel/Helper/NitroxUser.cs
- NitroxPatcher/Patches/Persistent/GameInput_SetupDefaultKeyboardBindings_Patch.cs
- NitroxPatcher/Patches/Persistent/GameSettings_SerializeInputSettings_Patch.cs
Fixes #1897 by making the GameSettings_SerializeInputSettings_Patch persistent not dynamic, such that it is ran on startup, not on world load.
Testing:
I have tested with no options file, an options file that doesn't contain our keybinds, and one that contains keybinds assigned to different keys, each one is replaced correctly in and out of game.
> Prevent keybind resetting on startup

- NitroxClient/Communication/NetworkingLayer/LiteNetLib/LiteNetLibClient.cs
- NitroxModel/Helper/NatHelper.cs
- NitroxModel/Helper/NetHelper.cs
- NitroxPatcher/Patches/Persistent/GameSettings_SerializeInputSettings_Patch.cs
- NitroxServer/Communication/LiteNetLib/LiteNetLibServer.cs
Every commit targets a small improvement.
> Reducing allocations and error handling improvements

- Nitrox.Test/Model/Helper/NetHelperTest.cs
- NitroxModel/Helper/NetHelper.cs
- NitroxServer/Communication/Packets/Processors/PlayerJoiningMultiplayerSessionProcessor.cs
Previously this only worked for 127.x.x.x range IPs but now also works for LAN ipv4 and ipv6 IPs.
> Improved grant local admin to allow all IPs that will loop back

- Directory.Build.props
[https://learn.microsoft.com/fr-fr/dotnet/csharp/language-reference/compiler-options/code-generation](https://learn.microsoft.com/fr-fr/dotnet/csharp/language-reference/compiler-options/code-generation)
Debug symbols will be emitted directly in .dll/.exe instead of outside, resulting in bunch on .pdb files
> Avoid generating .pdb files

- NitroxClient/ClientAutoFacRegistrar.cs
- NitroxClient/Communication/PacketSuppression.cs
- NitroxClient/Communication/Packets/Processors/InitialPlayerSyncProcessor.cs
- NitroxClient/GameLogic/InitialSync/Abstract/IInitialSyncProcessor.cs
- NitroxClient/GameLogic/InitialSync/Abstract/InitialSyncProcessor.cs
- NitroxClient/GameLogic/InitialSync/EquippedItemInitialSyncProcessor.cs
- NitroxClient/GameLogic/InitialSync/GlobalRootInitialSyncProcessor.cs
- NitroxClient/GameLogic/InitialSync/PdaInitialSyncProcessor.cs
- NitroxClient/GameLogic/InitialSync/PlayerInitialSyncProcessor.cs
- NitroxClient/GameLogic/InitialSync/PlayerPositionInitialSyncProcessor.cs
- NitroxClient/GameLogic/InitialSync/PlayerPreferencesInitialSyncProcessor.cs
- NitroxClient/GameLogic/InitialSync/QuickSlotInitialSyncProcessor.cs
- NitroxClient/GameLogic/InitialSync/RemotePlayerInitialSyncProcessor.cs
- NitroxClient/GameLogic/InitialSync/SimulationOwnershipInitialSyncProcessor.cs
- NitroxClient/GameLogic/InitialSync/StoryGoalInitialSyncProcessor.cs
- Made dependencies in InitSyncProcessors type checked for being an InitSyncProcessor.
- Removed two instances of bad DI usage (inline resolve instead of ctor parameter) for:
- `LocalPlayer` in `PlayerInitialSyncProcessor`
- `TimeManager` in `StoryGoalInitialSyncProcessor`
- Fixed an equality check on `goal` which should be on its `goal.Key` in `StoryGoalInitialSyncProcessor`
- Removed an usused local variable in `StoryGoalInitialSyncProcessor`:
- `List<string> goalKeys = scheduledGoals.ConvertAll((goal) => goal.GoalKey);`
- Minor edits to progress calculations in `SimulationOwnershipInitialSyncProcessor`
- Used "file-scoped namespace" syntax in all `InitialSyncProcessor` related types.
> Code clean up initial sync processors

- NitroxLauncher/LauncherLogic.cs
- NitroxModel/Platforms/OS/Shared/ProcessEx.cs
- NitroxModel/Platforms/Store/MSStore.cs
- NitroxPatcher/Patches/Dynamic/Application_IsFocused_Patch.cs
- NitroxPatcher/Patches/Persistent/GameAnalytics_Patch.cs
MS Store game files no longer needs to be unpacked as before, so we can support it. Code differences between Steam/Epic and MS Store are minimal.
> Enable MS Store support

- Nitrox.Test/Patcher/Patches/Dynamic/SpawnConsoleCommand_OnConsoleCommand_PatchTest.cs
- Nitrox.Test/Patcher/Patches/Dynamic/SubConsoleCommand_OnConsoleCommand_sub_PatchTest.cs
- NitroxClient/GameLogic/MobileVehicleBay.cs
- NitroxClient/GameLogic/NitroxConsole.cs
- NitroxClient/GameLogic/Vehicles.cs
- NitroxPatcher/Patches/Dynamic/SpawnConsoleCommand_OnConsoleCommand_Patch.cs
- NitroxPatcher/Patches/Dynamic/SpawnConsoleCommand_SpawnAsync_Patch.cs
- NitroxPatcher/Patches/Dynamic/SubConsoleCommand_OnConsoleCommand_sub_Patch.cs
~~- [ ] Maybe:  Move those to command callbacks ("/spawn [VEHICLE TYPE] [OPTIONAL COORDINATES]") with OP requirement~~
Adds the translation key: "Nitrox_MissingPermission" to be set like so
"You miss the permissions to execute this command [{PERMISSION}]"
> Sync spawning commands

- NitroxModel/NitroxModel.csproj
- NitroxServer/Communication/LiteNetLib/LiteNetLibConnection.cs
- NitroxServer/Communication/LiteNetLib/LiteNetLibServer.cs
- NitroxServer/Communication/NitroxConnection.cs
- NitroxServer/Communication/NitroxServer.cs
- NitroxServer/Communication/Packets/PacketHandler.cs
- NitroxServer/Communication/Packets/Processors/Abstract/UnauthenticatedPacketProcessor.cs
- NitroxServer/Communication/Packets/Processors/MultiplayerSessionPolicyRequestProcessor.cs
- NitroxServer/Communication/Packets/Processors/MultiplayerSessionReservationRequestProcessor.cs
- NitroxServer/Communication/Packets/Processors/PlayerJoiningMultiplayerSessionProcessor.cs
- NitroxServer/GameLogic/InitialSyncTimerData.cs
- NitroxServer/GameLogic/PlayerManager.cs
- NitroxServer/Player.cs
peer is now deriving from IPEndpoint
https://github.com/RevenantX/LiteNetLib/releases/tag/v1.2.0
> Upgraded Litenetlib to 1.2.0

- NitroxClient/GameLogic/Spawning/InstalledModuleEntitySpawner.cs
- Fixes #1989 
- Apparent regression of inventory module not restoring inventory items upon server reload
- No code in `InstalledModuleEntitySpawner` indicates that it handles it's own children spawning
- Setting to false resolves the issue with Seamoth & Prawnsuit inventories not having their items placed in the chest
- Child spawning now managed by [https://github.com/SubnauticaNitrox/Nitrox/blob/cfc08f3cc1174e551bddfb2dabaec1f6f34cc1a3/NitroxClient/GameLogic/Entities.cs#L217](https://github.com/SubnauticaNitrox/Nitrox/blob/cfc08f3cc1174e551bddfb2dabaec1f6f34cc1a3/NitroxClient/GameLogic/Entities.cs#L217)
I am new to the project and definitely lack the context for the big picture of impact this change could produce, but I have validated all module related storage behaves as expected with …
> Fix for attached storage module inventory

- Directory.Build.props
- Directory.Build.targets
This was a regression from changing build process to a custom task. VS tried to resolve custom task during NuGet resolve but NuGet resolve is required to find the task, this lead to a kind of deadlock.
Closes #2171
> Fixed NuGet failing to resolve properly in Visual Studio

- NitroxClient/MonoBehaviours/Gui/Modals/Modal.cs
- Fixes issue #2157 
- Changes a method name to be more readable and adhere to the C# styling guidelines
Testing(what I have tested):
- All modals(KickedModal, ConfirmModal, LostConnnectionModal, and ServerStoppedModal)
- Other menu elements still function as intended
- Player is properly kicked and appears that way to server and other clients(player is actually removed from the game)
- Kicking player from both server console and an admin player in game displays the correct modal and kicks the player
- Abruptly killing the server(AltF4/taskkill /f) disconnects all players with the appropriate modal shown(LostConnectionModal)
- Stopping the server(using the stop command) disconnects all players with the appropriate modal shown(ServerStoppedModal)
> Fix for disconnection modal not showing

- Nitrox.Assets.Subnautica/Resources/SoundWhitelist_Subnautica.csv
- Nitrox.Test/Model/DataStructures/Util/OptionalTest.cs
- Nitrox.Test/Patcher/Patches/Dynamic/FootstepSounds_OnStep_PatchTest.cs
- NitroxClient/Communication/Packets/Processors/FootstepPacketProcessor.cs
- NitroxModel/DataStructures/Optional.cs
- NitroxModel/Packets/FootstepPacket.cs
- NitroxPatcher/Patches/Dynamic/FootstepSounds_OnStep_Patch.cs
- NitroxServer/Communication/Packets/Processors/FootstepPacketProcessor.cs
Fixes issue #2164 
Does what the title says
- Footstep audio radius is currently set to 20m feel free to change it depending on your preference
- Footstep max audio multiplier is 0.5f, once again feel free to change it depending on your preference
- Server checks for same structure and will not send footstep packets to players who are outside of the sending player's structure
- Footstep sound volume scales with distance
- Uses reflection to create and send footstep packet when local game plays footstep sound
> Sync footstep audio

- NitroxClient/GameLogic/ChatUI/PlayerChatManager.cs
- NitroxClient/MonoBehaviours/Gui/Chat/PlayerChatInputField.cs
> Chat Deselection Workflow

- Nitrox.Test/Helper/Faker/NitroxCollectionFaker.cs
- Nitrox.Test/Patcher/Patches/PatchesTranspilerTest.cs
- Nitrox.sln.DotSettings
- NitroxClient/Communication/Packets/Processors/SetIntroCinematicModeProcessor.cs
- NitroxClient/GameLogic/HUD/PdaTabs/uGUI_PlayerListTab.cs
- NitroxClient/GameLogic/InitialSync/PlayerInitialSyncProcessor.cs
- NitroxClient/GameLogic/LocalPlayer.cs
- NitroxClient/GameLogic/PlayerLogic/PlayerCinematics.cs
- NitroxClient/GameLogic/PlayerManager.cs
- NitroxClient/GameLogic/Spawning/WorldEntities/EscapePodWorldEntitySpawner.cs
- NitroxClient/MonoBehaviours/AnimationController.cs
- NitroxClient/MonoBehaviours/CinematicController/MultiplayerCinematicReference.cs
- NitroxClient/MonoBehaviours/IntroCinematicUpdater.cs
- NitroxClient/MonoBehaviours/Multiplayer.cs
- NitroxModel/DataStructures/GameLogic/IntroCinematicMode.cs
- NitroxModel/MultiplayerSession/PlayerContext.cs
- NitroxModel/Packets/InitialPlayerSync.cs
- NitroxModel/Packets/SetIntroCinematicMode.cs
- NitroxPatcher/Patches/Dynamic/EscapePod_Start_Patch.cs
- NitroxPatcher/Patches/Dynamic/EscapePod_StopIntroCinematic_Patch.cs
- NitroxPatcher/Patches/Dynamic/uGUI_SceneIntro_HandleInput_Patch.cs
- NitroxPatcher/Patches/Dynamic/uGUI_SceneIntro_IntroSequence_Patch.cs
- NitroxPatcher/Patches/Dynamic/uGUI_SceneIntro_Stop_Patch.cs
- NitroxPatcher/Patches/Persistent/MainGameController_ShouldPlayIntro_Patch.cs
- NitroxPatcher/TranspilerHelper.cs
- NitroxServer/Communication/Packets/Processors/PlayerJoiningMultiplayerSessionProcessor.cs
- NitroxServer/Communication/Packets/Processors/SetIntroCinematicModeProcessor.cs
- NitroxServer/GameLogic/PlayerManager.cs
https://cdn.discordapp.com/attachments/1038497385208365177/1120414323932680282/2023-06-19_20-03-44.mp4
> Intro cinematic sync

- Nitrox.Test/Patcher/Patches/PatchesTranspilerTest.cs
- NitroxModel/Packets/VehicleMovements.cs
There are still two unit tests (PacketSerializationTest and PacketProcessorTest) that pass when ran individually but fail when ran alongside all the other tests. This might be due to race conditions or problems with how assemblies get loaded during tests.
> Make sure all unit tests are passing

- NitroxServer-Subnautica/Resources/Parsers/PrefabPlaceholderGroupsParser.cs
- NitroxServer-Subnautica/Resources/ResourceAssets.cs
- NitroxServer-Subnautica/Resources/ResourceAssetsParser.cs
- NitroxServer-Subnautica/SubnauticaServerAutoFacRegistrar.cs
- NitroxServer/GameLogic/Bases/BuildingManager.cs
- NitroxServer/GameLogic/Entities/NitroxEntitySlot.cs
- NitroxServer/GameLogic/Entities/Spawning/BatchEntitySpawner.cs
- NitroxServer/GameLogic/Entities/WorldEntityManager.cs
- NitroxServer/Resources/PrefabPlaceholderAsset.cs
- NitroxServer/Resources/PrefabPlaceholdersGroupAsset.cs
- NitroxServer/Resources/RandomSpawnSpoofer.cs
- NitroxServer/Serialization/World/WorldPersistence.cs
> Fix some entities wrongly treated by server

- NitroxClient/Communication/Packets/Processors/PlayerTeleportedProcessor.cs
- NitroxPatcher/Patches/Dynamic/GotoConsoleCommand_GotoPosition_Patch.cs
- NitroxPatcher/Patches/Dynamic/Player_WarpForward_Patch.cs
Attempting to modify the vehicle teleport behaviour.
Correctly updates player pos with player in seamoth / prawn
> Modify teleport to move vehicle

- NitroxPatcher/Patches/Dynamic/CyclopsHelmHUDManager_Update_Patch.cs
Seems to just be an issue of the state never being initially effected, or maybe some sort of race condition due to coroutines being used to effect the change in states? Likely will never know, I couldn't find the source myself. The CyclopsHelmHUDManager already sets the engine off text in its update loop, so I just added a bit to the existing Postfix patch for the method to also set the animator trigger that controls the engine speed menu.
> Fix engine speed menu being enabled when engine is off

- NitroxClient/MonoBehaviours/Gui/MainMenu/ServerJoin/JoinServerBackend.cs
- NitroxClient/MonoBehaviours/Gui/MainMenu/ServerJoin/MainMenuEnterPasswordPanel.cs
- NitroxClient/MonoBehaviours/Gui/MainMenu/ServerJoin/MainMenuJoinServerPanel.cs
- When the "join server" menu is opened, the player name input field is automatically focused with the cursor at the end
- Pressing enter inside the input field joins the server
I also want to look into a system that automatically deduplicates names for when I open two clients at once. I don't know the best way to do that though. Maybe the client could have the server check if their username is taken, and if it is, the server responds with an alternative username that the client could use.
Closes #2224
Closes #2225
> UI improvements for player name input

- Nitrox.sln
When cleaning .vs or starting from a new install, NitroxModel will always be choosen first by the IDE because it's the first project inside the .sln file.
I reordered the project inside the .sln and put Nitrox.Launcher on top of the list so the IDE will choose it first.
> Fix default startup project

- Nitrox.Launcher/App.axaml
- Nitrox.Launcher/Models/Behaviors/FocusOnViewShowBehavior.cs
- Nitrox.Launcher/Models/Design/IRoutingScreen.cs
- Nitrox.Launcher/Models/Design/RoutingScreen.cs
- Nitrox.Launcher/Models/Extensions/ScreenExtensions.cs
- Nitrox.Launcher/Models/Messages.cs
- Nitrox.Launcher/ViewModels/EmbeddedServerViewModel.cs
- Nitrox.Launcher/Views/CreateServerModal.axaml
- Nitrox.Launcher/Views/EmbeddedServerView.axaml
- Nitrox.Launcher/Views/LaunchGameView.axaml
- Nitrox.Launcher/Views/MainWindow.axaml
- Nitrox.Launcher/Views/ManageServerView.axaml
* Application name is overriden by informations we provide inside Info.plist upon macOS publish, but does not work inside IDE since this file does not exist
* Provide a basic native menu on macOS to avoid Avalonia emitting a default menu that displays a popup Nitrox is not aware and compatible of
* OnPlatform does not properly work with semi-binding, static providers, causing NRE on macOS
> macOS fixes

- NitroxModel/Helper/NitroxUser.cs
When inside the wine environment `Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData)` points to the very nested virtual wine folder. With this change Nitrox detects the wine environment and returns the dir normally used on linux.
> Get correct ApplicationData dir on linux/wine

- NitroxPatcher/Patches/Dynamic/EscapePod_RespawnPlayer_Patch.cs
- NitroxPatcher/Patches/Dynamic/Player_MovePlayerToRespawnPoint_Patch.cs
Fixes issue #2238:
"warpme" command now correctly broadcasts the EscapePodChange packet when teleporting the player into the lifepod.
Adds patch (EscapePod_RespawnPlayer_Patch) to hook the function that respawns the player into the lifepod, either after a death or a "warpme".
Now-redundant code removed from Player_MovePlayerToRespawnPoint_Patch.
> Fix warpme command not sending escape pod changed packet

- Nitrox.Launcher/Models/Extensions/ServiceCollectionExtensions.cs
- Nitrox.Launcher/Nitrox.Launcher.csproj
- Nitrox.Launcher/ViewModels/Abstract/ViewModelBase.cs
Added error if empty ViewModel constructor is called while a non-empty exists. This meant that the DI container couldn't resolve all the constructor parameters.
> Added auto registration of Views, ViewModels and Dialogs for launcher

- NitroxClient/Communication/Packets/Processors/BuildingResyncProcessor.cs
- NitroxClient/GameLogic/Spawning/Bases/ModuleEntitySpawner.cs
- NitroxClient/GameLogic/Spawning/InstalledModuleEntitySpawner.cs
- NitroxPatcher/Patches/Dynamic/Pickupable_OnDestroy_Patch.cs
Fixes issue #2318 where batteries and power cells would disappear after rejoining the game or using the building resync feature.
`ModuleEntitySpawner` now spawns `InstalledModuleEntity` child entities as well as `InventoryItemEntity`. Previously batteries/powercells would not be spawned because of this.
~When the charger was restored in preparation for the resync it would broadcast `ModuleRemoved` for each battery and cause them to be lost. `InstalledModuleEntitySpawner` now uses the `Equipment.AddItem()` method instead of inlining the same steps, which broadcasts `ModuleAdded`.~
> Fixes #2318, battery/power cell in chargers disappearing on resync

- NitroxPatcher/Patches/Dynamic/PlayerCinematicController_OnPlayerCinematicModeEnd_Patch.cs
- NitroxPatcher/Patches/Dynamic/PlayerCinematicController_StartCinematicMode_Patch.cs
- NitroxPatcher/Patches/Dynamic/PlayerCinematicController_Start_Patch.cs
With the ongoing attempt to sync player animations, several interactions are broken. We decided to temporarily disable these changes for the upcoming 1.8 release and spend more time finding a proper fix once the update is out.
Fixes #2287
> Temporarily disable PlayerCinematicController patches

- NitroxClient/GameLogic/Spawning/Metadata/Processor/SeamothMetadataProcessor.cs
- NitroxServer/Communication/Packets/Processors/DefaultServerPacketProcessor.cs
The seamoth light sound played globally for all players. This PR should fix that issue, as can be heard in the video below:
https://github.com/user-attachments/assets/e3a8b5a8-7851-4e53-a80f-488575651162
Note: The Seamoth light on sound still plays globally when a player inserts a power cell into an unpowered Seamoth, but that issue is much less annoying to deal with than someone spamming the Seamoth lights.
> Fix global Seamoth light sound

- NitroxClient/GameLogic/PlayerManager.cs
I was not able to reproduce the issue in question since this particular error seems to arise from a narrow race condition. However, it seems fairly straightforward to see where the issue occurs.
The `ChekItemsOnHashSet()` signature is defined as:
```cs
private void ChekItemsOnHashSet(
HashSet<GameObject> checkList,
CyclopsSonarDisplay.EntityType entityType)
```
Given that `entityType` is always defined in `CyclopsSonarCreatureDetector_CheckForCreaturesInRange_Patch.Postfix`, it's clear that `checkList` is receiving a null value in its HashSet.
The HashSet passed by the `Postfix` is `Resolve<PlayerManager>().GetAllPlayerObjects()`:
```cs
__instance.ChekItemsOnHashSet(Resolve<PlayerManager>().GetAllPlayerObjects(), PLAYER_TYPE);
```
Previously, `GetAllPlayerObjects()` retrieved every player …
> Add null reference check when getting all player objects

- NitroxClient/GameLogic/Spawning/Metadata/Processor/PlayerMetadataProcessor.cs
While testing #2359, I noticed that there is a log that is often spam : 
Which doesn't give any useful infos
> Removed UpdateForPlayer log spam

- NitroxPatcher/Patches/Dynamic/TimeCapsule_Open_Patch.cs
Adds a patch to send an `EntityDestroyed` packet when the player opens a time capsule. This removes the entity from the server's registry, so it won't reappear when that player or another player reenters the area.
The change to `EntityDestroyedPacketProcessor` in #2368 is not necessary, since time capsules are spawned by the server and not by the client. The client does not need to receive `EntityDestroyed` packets for entities it can't see, since the server will omit that entity from `SpawnEntities` if they load that cell, meaning the entity will not respawn. (Confirmed with testing)
Fixes #2357
> Destroy time capsules server-side when opened

- Nitrox.Launcher/Models/HttpDelegatingHandlers/FileCacheDelegatingHandler.cs
- Nitrox.Launcher/Models/Utils/Hashing.cs
- Nitrox.Shared.targets
- NitroxModel/Helper/NitroxUser.cs
- NitroxModel/Logger/Log.cs
- NitroxPatcher/Patches/Persistent/ScreenshotManager_Initialise.Path.cs
- NitroxServer-Subnautica/Resources/Parsers/PrefabPlaceholderGroupsParser.cs
Currently the folder look like this
"screenshots" is hardcoded inside Subnautica's code and would required multiple transpilers to get rid of. Since "saves" is already in lower, I decided to lowered the 2 others as well
> Moved Screenshots Path to Nitrox AppData

- NitroxClient/Communication/Packets/Processors/PlayerTeleportedProcessor.cs
- NitroxClient/GameLogic/InitialSync/PlayerPositionInitialSyncProcessor.cs
- NitroxClient/GameLogic/Terrain.cs
Make it so all of the WaitForWorldLoad are actually backed up by an unfreeze if they fail.
> Fix potential player freeze after initial sync

- NitroxModel/Helper/NatHelper.cs
- NitroxModel/Helper/NetHelper.cs
- NitroxServer/Communication/Packets/Processors/DiscordRequestIPProcessor.cs
- NitroxServer/Server.cs
This PR adds the RadminVPN IP to the server IP list if the app is running. Also refactored the function to make it easier to add other VPNs in the future should we decide to do so, assuming that getting their IPs work the same way as they do for Hamachi and Radmin.
Tested it out on my machine and it works, though I am not sure if there would be any issues if both Hamachi and Radmin are running at the same time as I don't have Hamachi installed (but I don't think this will be the case for most users).
> Show RadminVPN IP in server console

- NitroxClient/GameLogic/Spawning/WorldEntities/GlobalRootEntitySpawner.cs
Title says it all
My fix applies another step to GlobalRootEntity spawning, in the case of spawning inside of a water park. Cell level will be set to initial cell level which corresponds to the prefab's relevant cell level. Because all global root entities have their cell entities automatically set to GlobalRoot (from a previous PR of mine), we now have to manage this precise case.
In case you happened to run into this issue before this is merged, you can look through your EntityData.json for all entities of type WorldEntity with a cell level of 100 and set their it to something like 1 or just remove them if you don't need em.
Fixes #2450
> Fix water park fishes having a global root cell level

- NitroxClient/GameLogic/InitialSync/PlayerInitialSyncProcessor.cs
- NitroxPatcher/Patches/Dynamic/EscapePod_OnConsoleCommand_randomstart_Patch.cs
- NitroxPatcher/Patches/Dynamic/EscapePod_StartAtPosition_Patch.cs
Context: Regressed in #2321
Context : 
In #2321 we did change the entrypoint ofescapepod changed packet in order to sync more behavior. However it did show up some path where SN doing some init code for escapepod position and player position during Subnautica boot. Which Nitrox is already doing behind the hood.
So I did suppress this code that shouldn't be called by Subnautica
> Fix unauthenticated EscapePodChanged packet upon joining
