NitroxClient/GameLogic/PlayerGameObjectManager.cs, NitroxClient/MonoBehaviours/Multiplayer.cs
- Should de disabled in a later release, but is really helpful for
debugging.
=> Warpto debug command to teleport to other player.

NitroxClient/Communication/Packets/Processors/EquipmentAddItemProcessor.cs, NitroxClient/Communication/Packets/Processors/EquipmentRemoveItemProcessor.cs, NitroxClient/MonoBehaviours/Gui/Input/KeyBindingManager.cs, NitroxClient/MonoBehaviours/Gui/Input/KeyBindings/Actions/ChatKeyBindingAction.cs, NitroxClient/MonoBehaviours/Gui/Input/KeyBindings/Actions/KeyBindingAction.cs, NitroxClient/MonoBehaviours/Gui/Input/KeyBindings/DefaultKeyBinding.cs, NitroxClient/MonoBehaviours/Gui/Input/KeyBindings/KeyBinding.cs, NitroxClient/MonoBehaviours/Gui/MainMenu/JoinServer.cs, NitroxClient/NitroxClient.csproj, NitroxModel/Helper/ReflectionHelper.cs, NitroxPatcher/NitroxPatcher.csproj, NitroxPatcher/Patches/ArmsController_Update_Patch.cs, NitroxPatcher/Patches/GameInput_Initialize_Patch.cs, NitroxPatcher/Patches/GameInput_SetupDefaultKeyboardBindings_Patch.cs, NitroxPatcher/Patches/GameSettings_SerializeInputSettings_Patch.cs, NitroxPatcher/Patches/Player_Update_Patch.cs, NitroxPatcher/Patches/uGUI_OptionsPanel_AddBindings_Patch.cs
Note that NitroxModel/Helper/ReflectionHelper.cs will need a refactor to follow qualifier chaining used elsewhere. This refactor was out of scope for this request and will likely be handled in a follow-up request.
=> Chat improvements

NitroxClient/Communication/Packets/Processors/AnimationProcessor.cs, NitroxClient/Communication/Packets/Processors/MovementProcessor.cs, NitroxClient/Communication/Packets/Processors/VehicleMovementProcessor.cs, NitroxClient/GameLogic/PlayerManager.cs, NitroxClient/MonoBehaviours/Multiplayer.cs, NitroxModel/DataStructures/Optional.cs, NitroxModel/Packets/Processors/Abstract/PacketProcessor.cs, NitroxReloader/Reloader.cs, NitroxReloader/ReloaderAssembly.cs
Follows https://github.com/Sunrunner37/Nitrox/pull/15.
Cleanups regarding comments.
I've never before used the `Optional<>` structure in imperative programming, only in functional programming, so I've added one of those constructs (and will add more soon). What is your opinion on this? I personally don't like the clutter (having a variable for the optional, then a condition, then another variable with the value that is held by the `Optional<>`).
Also, another question regarding formatting: spaces between an `if` statement and the open brace? (this applies to other control statements as well).
I have 34 matches of `if(` on master, and 245 of `if (`. My editor is set to insert it.
=> Cleanup #15

NitroxClient/Communication/Packets/Processors/CyclopsActivateHornProcessor.cs, NitroxClient/Communication/Packets/Processors/CyclopsActivateShieldProcessor.cs, NitroxClient/Communication/Packets/Processors/CyclopsBeginSilentRunningProcessor.cs, NitroxClient/GameLogic/Cyclops.cs, NitroxClient/NitroxClient.csproj, NitroxModel/NitroxModel.csproj, NitroxModel/Packets/CyclopsActivateHorn.cs, NitroxModel/Packets/CyclopsActivateShield.cs, NitroxPatcher/NitroxPatcher.csproj, NitroxPatcher/Patches/CyclopsHornButton_OnPress_Patch.cs, NitroxPatcher/Patches/CyclopsShieldButton_OnClick_Patch.cs
=> Cyclops Horn Sync

NitroxClient/Communication/ChunkAwarePacketReceiver.cs, NitroxClient/Communication/Packets/Processors/ToggleLightsProcessor.cs, NitroxClient/GameLogic/RemotePlayer.cs, NitroxClient/MonoBehaviours/SyncedMultiplayerObject.cs, NitroxModel/DataStructures/Surrogates/TechTypeSurrogate.cs, NitroxModel/Helper/GameLogic/GuidHelper.cs, NitroxModel/Packets/Processors/Abstract/PacketProcessor.cs, NitroxModel/Packets/VisibleChunksChanged.cs, NitroxPatcher/Patches/NitroxPatch.cs, NitroxServer/GameLogic/AI.cs, NitroxServer/GameLogic/ChunkManager.cs, NitroxServer/Player.cs, NitroxTest/Client/Communication/ChunkAwarePacketReceiverTest.cs, NitroxTest/Fakes/NitroxClient.fakes, NitroxTest/Model/PacketProcessorTest.cs, NitroxTest/NitroxTest.csproj
=> Post-merge cleanups.

.gitmodules
That way the protocol is determined by the parent repo instance.
=> Use relative submodule url

NitroxClient/Communication/Packets/Processors/CyclopsChangeEngineModeProcessor.cs, NitroxClient/Communication/Packets/Processors/CyclopsToggleEngineStateProcessor.cs, NitroxClient/GameLogic/Cyclops.cs, NitroxClient/NitroxClient.csproj, NitroxModel/NitroxModel.csproj, NitroxModel/Packets/CyclopsChangeEngineMode.cs, NitroxModel/Packets/CyclopsToggleEngineState.cs, NitroxPatcher/NitroxPatcher.csproj, NitroxPatcher/Patches/CyclopsEngineChangeState_OnClick_Patch.cs, NitroxPatcher/Patches/CyclopsHelmHUDManager_Patch.cs, NitroxPatcher/Patches/CyclopsMotorModeButton_OnClick_Patch.cs, NitroxPatcher/Patches/CyclopsMotorMode_SaveEngineStateAndPowerDown_Patch.cs
Merged from this pull requests
Engine state: https://github.com/SubnauticaNitrox/Nitrox/pull/38
Engine mode: https://github.com/SubnauticaNitrox/Nitrox/pull/39
HelmHUD: https://github.com/SubnauticaNitrox/Nitrox/pull/47
=> Sync Cyclops-MotorMode, -MotorState and -HUD

NitroxClient/Communication/DeferringPacketReceiver.cs, NitroxClient/GameLogic/RemotePlayer.cs, NitroxPatcher/Patches/ArmsController_Update_Patch.cs, NitroxTest/Model/PriorityQueueTest.cs
resubmitted, will test soon, feel free to fix any of my errors
=> fixed multiple bugs

NitroxClient/Communication/DeferringPacketReceiver.cs, NitroxClient/GameLogic/Helper/SerializationHelper.cs, NitroxClient/MonoBehaviours/AnimationController.cs, NitroxClient/MonoBehaviours/Gui/HUD/RemotePlayerVitals.cs, NitroxClient/Unity/Helper/DebugUtils.cs, NitroxPatcher/Patches/ArmsController_Start_Patch.cs, NitroxPatcher/Patches/ArmsController_Update_Patch.cs, NitroxPatcher/Patches/BaseGhost_Finish_Patch.cs, NitroxPatcher/Patches/ConstructorInput_OnCraftingBegin_Patch.cs, NitroxPatcher/Patches/NitroxPatch.cs, NitroxTest/Model/PriorityQueueTest.cs
Minor bugfixes and improvements. All the basic functionality should work on the latest version of subnautica.
=> Experimental b81 compatibility

NitroxClient/Communication/ClientBridge.cs, NitroxClient/Communication/DeferringPacketReceiver.cs, NitroxClient/Communication/IPacketSender.cs, NitroxClient/Communication/PacketSuppression.cs, NitroxClient/Communication/Packets/Processors/StoryEventHandler.cs, NitroxClient/NitroxClient.csproj, NitroxModel/Extensions.cs, NitroxModel/NitroxModel.csproj, NitroxModel/Packets/StoryEventSend.cs, NitroxPatcher/NitroxPatcher.csproj, NitroxTest/NitroxTest.csproj
Some small fixes cherry-picked/backported from the `autofac` branch - one of which was limiting/breaking the game experience.
=> Tiny bugfixes

NitroxClient/Communication/DeferringPacketReceiver.cs, NitroxClient/GameLogic/Terrain.cs, NitroxModel/NitroxModel.csproj, NitroxModel/Packets/ConstructionAmountChanged.cs, NitroxModel/Packets/ConstructionCompleted.cs, NitroxModel/Packets/DeconstructionBegin.cs, NitroxModel/Packets/DeconstructionCompleted.cs, NitroxModel/Packets/DeferrablePacket.cs, NitroxModel/Packets/DroppedItem.cs, NitroxModel/Packets/EquipmentAddItem.cs, NitroxModel/Packets/EquipmentRemoveItem.cs, NitroxModel/Packets/ItemContainerAdd.cs, NitroxModel/Packets/ItemContainerRemove.cs, NitroxModel/Packets/MedicalCabinetClicked.cs, NitroxModel/Packets/PickupItem.cs, NitroxModel/Packets/PlaceBasePiece.cs, NitroxModel/Packets/PlaceFurniture.cs, NitroxReloader/NitroxReloader.csproj, NitroxServer/Communication/Packets/PacketHandler.cs, NitroxServer/GameLogic/EntityManager.cs, NitroxServer/GameLogic/Spawning/EntitySpawnPoint.cs, NitroxServer/GameLogic/Spawning/EntitySpawner.cs, NitroxServer/Serialization/BatchCellsParser.cs, NitroxTest/Model/Test/TestActionPacket.cs
Depends on #171 
Lazyloads batches on the server, depending on the locations visited by clients. The original system took between 40 seconds to 2 minutes at full CPU load, on a relatively powerful quadcore machine.
Please review the locking carefully - it has been written to be more granular and allow more concurrency, though this may not be optimal in all cases.
=> Batch lazy loading

README.md
the possessive version of "it" is "its" not "it's"
=> Made README more grammatically correct

NitroxClient/MonoBehaviours/Gui/MainMenu/MainMenuMods.cs, NitroxClient/MonoBehaviours/Gui/MainMenu/MainMenuMultiplayerPanel.cs
=> corrects bugs introduced into the main menu bug to Subnautica update

NitroxClient/Communication/Packets/Processors/ConstructorBeginCraftingProcessor.cs, NitroxClient/GameLogic/LocalPlayer.cs, NitroxClient/GameLogic/PlayerModelBuilder/PlayerModelDirector.cs, NitroxClient/GameLogic/PlayerModelBuilder/RegularDiveSuitBuilder.cs, NitroxClient/GameLogic/RemotePlayer.cs, NitroxClient/MonoBehaviours/Gui/HUD/RemotePlayerVitals.cs, NitroxClient/MonoBehaviours/Gui/MainMenu/JoinServer.cs, NitroxClient/MonoBehaviours/Gui/MainMenu/MainMenuMods.cs, NitroxClient/MonoBehaviours/Gui/MainMenu/MainMenuMultiplayerPanel.cs, NitroxClient/Unity/Helper/DebugUtils.cs, NitroxClient/Unity/Helper/GameObjectHelper.cs
Fixes #194 
Fixes SN update regressions in two `Transform` paths, and implemented helper methods to identify missing objects rather than causing NRE's later on.
=> Fixed menu layout path, added RequireTransform/GameObject helper.

NitroxClient/MonoBehaviours/Gui/MainMenu/JoinServer.cs, NitroxClient/MonoBehaviours/Gui/MainMenu/MainMenuMods.cs, NitroxClient/MonoBehaviours/Gui/MainMenu/MainMenuMultiplayerPanel.cs
Destroy some TranslationLiveUpdate Components
Move/Put some lines (together)
=> MainMenu Button Fix

NitroxClient/Communication/Packets/Processors/EquipmentAddItemProcessor.cs, NitroxClient/Communication/Packets/Processors/InitialPlayerSyncProcessor.cs, NitroxClient/GameLogic/EquipmentSlots.cs, NitroxModel/DataStructures/GameLogic/ItemEquipment.cs, NitroxModel/NitroxModel.csproj, NitroxModel/Packets/EquipmentAddItem.cs, NitroxModel/Packets/InitialPlayerSync.cs, NitroxPatcher/NitroxPatcher.csproj, NitroxPatcher/Patches/Player_OnDestroy_Patch.cs, NitroxServer/GameLogic/Players/PlayerData.cs
=> Fix Player container wipe during the normal shutdown routine

NitroxClient/NitroxClient.csproj, NitroxModel/NitroxModel.csproj, NitroxPatcher/Patches/Persistent/EscapePodFirstUseCinematicsController_Initialize_Patch.cs, NitroxPatcher/Patches/Persistent/ProtobufSerializer_DeserializeIntoGameObject_Patch.cs
Fixes #236
Reorganized method keeping end result whilst filtering and removing duplicated materials.
=> * Fixed bug with flora spawn duplication

NitroxPatcher/Patches/Persistent/ProtobufSerializer_DeserializeIntoGameObject_Patch.cs
Mistyped an exclamation point...
=> Fixed major bug in previous PR

.editorconfig, NitroxServer/Program.cs
The squiggly lines gave me nightmares. Want to thank @killzoms for helping me looking into it.
=> Fixed local variables from pascal case to camel case (hopefully)..

NitroxClient/MonoBehaviours/Multiplayer.cs, NitroxInstaller/NitroxInstaller.wixproj, NitroxModel/Discovery/InstallationFinders/SteamGameRegistryFinder.cs, NitroxModel/Packets/ServerCommand.cs, NitroxServer/Communication/Packets/Processors/ServerCommandProcessor.cs, NitroxServer/ConsoleCommands/Abstract/Command.cs, NitroxServer/ConsoleCommands/ExitCommand.cs, NitroxServer/ConsoleCommands/Processor/ConsoleCommandProcessor.cs, NitroxServer/ConsoleCommands/SaveCommand.cs, NitroxServer/IpLogger.cs, NitroxServer/NitroxServer.csproj, NitroxServer/Program.cs, NitroxServer/Server.cs
Added server command processor to process commands typed into server console
=> Dunno why these commits were removed

NitroxServer.Wpf/ConsoleExecutor.cs, NitroxServer.Wpf/MainWindow.xaml.cs, NitroxServer/IpLogger.cs
Changed server IP discovery to be async.
Added send "exit" command to server on WPF window close.
=> Changed server ip discovery to be async.

NitroxInstaller/Product.wxs, NitroxInstallerActions/Patches/NitroxServerSetup.cs, NitroxInstallerActions/UninstallPatchAction.cs
Cleaned up the installer to make sure all files get deleted upon uninstall.
Added a NitroxServer uninstall routine to delete copied subnautica files.
Enforced priviliges on custom actions so they can be executed as admin. (Fixes #513 / #469 )
=> Cleaned up installer so it removes all files. 

NitroxClient/Communication/Packets/Processors/BroadcastEscapePodsProcessor.cs, NitroxClient/GameLogic/ItemContainers.cs, NitroxModel/DataStructures/GameLogic/EscapePodModel.cs, NitroxModel/path.txt, NitroxPatcher/Patches/ItemsContainer_NotifyAddItem_Patch.cs, NitroxPatcher/Patches/ItemsContainer_NotifyRemoveItem_Patch.cs, NitroxServer/Communication/Packets/PacketHandler.cs, NitroxServer/Communication/Packets/Processors/PlayerJoiningMultiplayerSessionProcessor.cs, NitroxServer/GameLogic/EscapePodData.cs, NitroxServer/GameLogic/EscapePodManager.cs, NitroxServer/NitroxServer.csproj, NitroxServer/Serialization/World/PersistedWorldData.cs, NitroxServer/Serialization/World/World.cs, NitroxServer/Serialization/World/WorldPersistence.cs
I could only test it by relogging and restarting the server, I could not try it with 2 players.
Edit: The storage box is now starting empty and I didn't managed to figure out how to put the starting items into it on world gen.
PS: I'm new to this code and I don't fully understand it, sorry if I broke something!
=> Got working the storage in the Escape Pod.

NitroxServer/App.config, NitroxServer/GameLogic/Entities/EntityData.cs, NitroxServer/GameLogic/Entities/EntityManager.cs, NitroxServer/Serialization/ServerConfig.cs, NitroxServer/Server.cs
Added Save Interval to app.config for later use with session settings also removed non required add on existing key in dict when throwing item.
=> Added Save Interval to app.config for later use with session settings

NitroxClient/MonoBehaviours/Gui/MainMenu/MainMenuMultiplayerPanel.cs
Auto reformatted the MP panel code.
=> Made multiplayer panel more clear on what it does for players.

NitroxClient/GameLogic/EquipmentSlots.cs
Only true change is line 28. Everything else is sort and remove usings and VS 2017 code formatting
=> Resolve inifinite oxygen bug when tank equipped at surface (#290)

NitroxClient/Debuggers/SceneDebugger.cs
~~WIP: Still need to invoke the selected method when you click "Invoke"..~~
Made gameobjects with children bold
Added method view for monobehaviour debugger where methods can be invoked if not having any parameters
=> Added gameobject name lookup to SceneDebugger.HierarchyTab

NitroxClient/MonoBehaviours/Gui/MainMenu/MainMenuMultiplayerPanel.cs, NitroxInstallerActions/Patches/NitroxServerSetup.cs, NitroxServer/Serialization/BatchCellsParser.cs, NitroxServer/Serialization/ResourceAssetsParser.cs
This patch fixed these hardcoded backslashes that caused the bug in *nix.
=> Linux Path Fix

NitroxClient/Communication/MultiplayerSession/MultiplayerSessionManager.cs, NitroxModel/Packets/MultiplayerSessionPolicy.cs, NitroxModel/Properties/AssemblyInfo.cs
Also used VS code formatting and remove and sort usings
=> Verify client version

NitroxPatcher/Main.cs, NitroxPatcher/Patches/NitroxPatch.cs, NitroxPatcher/Patches/Persistent/PAXTerrainController_LoadAsync_Patch.cs, NitroxTest/Patcher/Patches/BaseGhost_Finish_PatchTest.cs, NitroxTest/Patcher/Patches/BuilderPatchTest.cs, NitroxTest/Patcher/Patches/BuilderTool_HandleInput_PatchTest.cs, NitroxTest/Patcher/Patches/ConstructorInput_OnCraftingBegin_PatchTest.cs, NitroxTest/Patcher/Patches/Equipment_RemoveItem_PatchTest.cs, NitroxTest/Patcher/Test/PatchTestHelper.cs
This is a paired PR with https://github.com/SubnauticaNitrox/Harmony/pull/2
=> Updated Harmony

NitroxClient/GameLogic/Entities.cs, NitroxClient/GameLogic/Spawning/DefaultEntitySpawner.cs, NitroxClient/GameLogic/Spawning/SerializedEntitySpawner.cs, NitroxModel/DataStructures/GameLogic/Entity.cs, NitroxServer/Communication/Packets/Processors/DroppedItemPacketProcessor.cs, NitroxServer/GameLogic/Entities/Spawning/BatchEntitySpawner.cs, NitroxServer/GameLogic/Entities/Spawning/EntityBootstrappers/CrashFishBootstrapper.cs, NitroxServer/GameLogic/Entities/Spawning/EntityBootstrappers/ReefbackBootstrapper.cs, NitroxServer/GameLogic/Entities/Spawning/EntitySpawnPoint.cs, NitroxServer/Serialization/BatchCellsParser.cs, NitroxServer/Serialization/ServerProtobufSerializer.cs, NitroxServer/Serialization/World/PersistedWorldData.cs, NitroxServer/Serialization/World/WorldPersistence.cs, NitroxServer/ServerAutoFacRegistrar.cs
Edit:
GameObject scaling has been included now
=> Bug with double parsing of ingame files and object scaling

NitroxClient/Unity/Helper/DebugUtils.cs, NitroxClient/Unity/Helper/GameObjectHelper.cs, NitroxPatcher/Patches/ToggleLights_SetLightsActive_Patch.cs
Round two. Clean branch, no commit clutter.
=> Updated debugutils

NitroxModel/NitroxModel.csproj, NitroxModel/packages.config
Thought Subnautica was using log4net. *blame me*
Added the Nuget package for log4net and now everything should work as expected.
=> Added missing log4net dependency

NitroxClient/MonoBehaviours/Gui/Chat/PlayerChatLog.cs, NitroxServer/App.config, NitroxServer/ConsoleCommands/ChangeAdminPasswordCommand.cs, NitroxServer/ConsoleCommands/LoginCommand.cs, NitroxServer/NitroxServer.csproj, NitroxServer/Serialization/ServerConfig.cs, NitroxServer/Serialization/World/WorldPersistence.cs
Adds an admin login through chat rather then having someone to do it through console. Also fixes to the layout.
=> Adds Admin login & fixes to Chat

NitroxModel/NitroxModel.csproj, NitroxModel/Packets/BedEnter.cs, NitroxPatcher/NitroxPatcher.csproj, NitroxPatcher/Patches/Bed_EnterInUseMode_Patch.cs, NitroxPatcher/Patches/DayNightCycle_OnConsoleCommand_day_Patch.cs, NitroxPatcher/Patches/DayNightCycle_OnConsoleCommand_night_Patch.cs, NitroxServer/Communication/Packets/Processors/BedEnterProcessor.cs, NitroxServer/Communication/Packets/Processors/PlayerJoiningMultiplayerSessionProcessor.cs, NitroxServer/ConsoleCommands/DayCommand.cs, NitroxServer/ConsoleCommands/NightCommand.cs, NitroxServer/GameLogic/TimeKeeper.cs, NitroxServer/NitroxServer.csproj
Also blocked the day/night commands on the client.
=> Added day/night commands and syncing bed behavior

NitroxServer/GameLogic/Entities/Spawning/BatchEntitySpawner.cs, NitroxServer/GameLogic/Entities/Spawning/EntitySpawnPoint.cs, NitroxServer/Serialization/BatchCellsParser.cs
=> Fixed EntitySlotsPlaceholder spawning

NitroxClient/Debuggers/SceneDebugger.cs
=> Add Component searching to the SceneDebugger

NitroxClient/Debuggers/SceneDebugger.cs
excluding "override collider" and "Player" from raycast.
Disclaimer: Inside the aurora you will still get a lot of hits of the Room cube.
=> add full hitlist on Hierarchy tab on f9 raycast

NitroxServer/ConsoleCommands/ChangeAdminPasswordCommand.cs, NitroxServer/Serialization/ServerConfig.cs, NitroxServer/Serialization/World/WorldPersistence.cs
* Fixes bug with not being able to log in using default generated password
* Fixes **login** command after changing password after server start
* Allows **changepassword** command to be run via server console
=> Fix server password generation & change in console

NitroxInstaller/Product.wxs, NitroxServer/Serialization/ResourceAssetsParser.cs, NitroxServer/Server.cs
=> Multiple minor fixes

NitroxClient/Communication/Packets/Processors/VehicleColorChangeProcessor.cs, NitroxClient/Communication/Packets/Processors/VehicleNameChangeProcessor.cs, NitroxClient/GameLogic/Constructor.cs, NitroxClient/GameLogic/Vehicles.cs
Fixes the Rocket base from breaking the server due incorrect checks in vehicle creation. Also fixes to the default colours and names so they are correct.
=> Fixes to Rocket base and default colours/names

NitroxServer/App.config, NitroxServer/GameLogic/PlayerManager.cs, NitroxServer/Serialization/ServerConfig.cs, NitroxServer/Serialization/World/WorldPersistence.cs
Refactor ServerConfig
Enforce MaxConnections limit on NitroxServer
Protect server side with config key ServerPassword (only implemented on server side)
@killzoms mentioned it (MaxConnections) on discord so i guess i need to notify him about this pr.
=> ServerConfig refactoring and enforcement

NitroxModel/MultiplayerSession/AuthenticationContext.cs, NitroxServer/App.config, NitroxServer/ConsoleCommands/ChangeServerPasswordCommand.cs, NitroxServer/ConsoleCommands/LoginCommand.cs, NitroxServer/GameLogic/PlayerManager.cs, NitroxServer/NitroxServer.csproj, NitroxServer/Serialization/ServerConfig.cs, NitroxServer/Serialization/World/WorldPersistence.cs
change password in AuthContext to Option.OfNullable
rename ServerAdminPassword to AdminPassword to avoid confusion with ServerPassword
tested.
the next PR will be about /help command
=> Add support for command ChangeServerPassword

NitroxServer/ConsoleCommands/Abstract/Command.cs, NitroxServer/ConsoleCommands/DayCommand.cs, NitroxServer/ConsoleCommands/DeopCommand.cs, NitroxServer/ConsoleCommands/ExitCommand.cs, NitroxServer/ConsoleCommands/HelpCommand.cs, NitroxServer/ConsoleCommands/LoginCommand.cs, NitroxServer/ConsoleCommands/NightCommand.cs, NitroxServer/ConsoleCommands/OpCommand.cs, NitroxServer/ConsoleCommands/WhisperCommand.cs, NitroxServer/NitroxServer.csproj, NitroxServer/Serialization/World/WorldPersistence.cs
the output is split into lines due to text length restriction on the client side.
feature tested.
btw chatlog box is a little bit small for an active chat.
=> Add support for command Help

NitroxClient/Communication/Packets/Processors/CyclopsFireSuppressionProcessor.cs, NitroxClient/Communication/Packets/Processors/VehicleDockingProcessor.cs, NitroxClient/Communication/Packets/Processors/VehicleUndockingProcessor.cs, NitroxClient/GameLogic/Cyclops.cs, NitroxClient/GameLogic/Vehicles.cs, NitroxClient/NitroxClient.csproj, NitroxModel-Subnautica/NitroxModel-Subnautica.csproj, NitroxModel-Subnautica/Packets/CyclopsFireSuppression.cs, NitroxPatcher/NitroxPatcher.csproj, NitroxPatcher/Patches/CyclopsFireSuppressionButton_StartCooldown_Patch.cs, NitroxPatcher/Patches/VehicleDockingBay_DockVehicle_Patch.cs, NitroxServer-Subnautica/NitroxServer-Subnautica.csproj, NitroxServer/Communication/Packets/Processors/VehicleDockingProcessor.cs
Features:
- Add missing pieces for the csproj files.
- fixes references (from IzmoIzmi's PR #741 )
- fire suppression synchronization for the cyclops now works.
- Cyclops vehicle docking now working
There are minor problems with docking:
- docking into a cyclops will play the docking sounds for all player regardless of position. Super hard to find where the sounds come from
- Undocking will just release the vehicle after the animation are played for the person in the vehicle. Looks terrible but works just fine
=> More Cyclops synchs

NitroxClient/Communication/Packets/Processors/RadioPlayPendingMessageProcessor.cs, NitroxClient/GameLogic/InitialSync/StoryGoalInitialSyncProcessor.cs, NitroxClient/NitroxClient.csproj, NitroxModel/DataStructures/GameLogic/InitialStoryGoalData.cs, NitroxModel/NitroxModel.csproj, NitroxModel/Packets/InitialPlayerSync.cs, NitroxModel/Packets/RadioPlayPendingMessage.cs, NitroxPatcher/NitroxPatcher.csproj, NitroxPatcher/Patches/Radio_PlayRadioMessage_Patch.cs, NitroxPatcher/Patches/StoryGoal_Execute_Patch.cs, NitroxServer/Communication/Packets/Processors/PlayerJoiningMultiplayerSessionProcessor.cs, NitroxServer/Communication/Packets/Processors/RadioPlayPendingMessageProcessor.cs, NitroxServer/Communication/Packets/Processors/StoryEventSendProcessor.cs, NitroxServer/GameLogic/GameData.cs, NitroxServer/GameLogic/Unlockables/StoryGoalData.cs, NitroxServer/NitroxServer.csproj, NitroxServer/Serialization/World/WorldPersistence.cs, NitroxServer/ServerAutoFacRegistrar.cs
The story goals are now synced between players and persist.
Also synced the radio queue and the playing of radio messages.
=> Basic story and radio sync

NitroxClient/Communication/NetworkingLayer/Lidgren/LidgrenClient.cs, NitroxClient/Communication/NetworkingLayer/ModulatingClient.cs, NitroxServer/Communication/NetworkingLayer/Lidgren/LidgrenServer.cs
- changed retrieving of Message.data
- changed .SendBuffer Size
~~- switched default Client-Communication to LiteNetLib and Lidgren as fallback~~
=> Simple Lidgren Fix

NitroxLauncher/NitroxLauncher.csproj, NitroxLauncher/packages.config, NitroxServer-Subnautica/App.config, NitroxServer/App.config, NitroxServer/Server.cs
=> dnlib pakage missing

NitroxLauncher/LauncherLogic.cs, NitroxLauncher/MainWindow.xaml.cs, NitroxLauncher/OptionPage.xaml, NitroxLauncher/Patching/PlatformDetection.cs, NitroxLauncher/Properties/AssemblyInfo.cs, NitroxLauncher/ServerPage.xaml.cs
Also some logic to let the launcher live as long as there is a running instance of client or server
=> Patch remove after Subnautica close

NitroxLauncher/MainWindow.xaml
Added some Chrome to allow the launcher window to be repositioned
=> Added WindowChrome to Launcher

NitroxLauncher/LauncherLogic.cs, NitroxLauncher/MainWindow.xaml, NitroxLauncher/MainWindow.xaml.cs, NitroxLauncher/NitroxLauncher.csproj, NitroxLauncher/ServerConsolePage.xaml, NitroxLauncher/ServerConsolePage.xaml.cs, NitroxLauncher/ServerPage.xaml, NitroxLauncher/ServerPage.xaml.cs, NitroxServer-Subnautica/App.config
- Server in console possible. Also normal version possible.
- Now always displays current version.
- Removes patch, when launcher will be closed
- Refactoring of MainWindow code
- Also removed the second appconfig from server executable
=> Server console in launcher

NitroxLauncher/ServerConsolePage.xaml
* - Add text wrap to prevent loss of long console messages without spaces
=> Add text wrap to server console

NitroxLauncher/LaunchGamePage.xaml, NitroxLauncher/MainWindow.xaml, NitroxLauncher/MainWindow.xaml.cs, NitroxLauncher/NitroxLauncher.csproj, NitroxLauncher/OptionPage.xaml, NitroxLauncher/ServerConsolePage.xaml, NitroxLauncher/ServerPage.xaml
- fixed that combobox is white for win8/10
- fixed white line on the right
- Nav buttons are not left aligned
=> Win10 combo box fix

NitroxLauncher/LaunchGamePage.xaml, NitroxLauncher/MainWindow.xaml, NitroxLauncher/OptionPage.xaml, NitroxLauncher/ServerPage.xaml, NitroxServer-Subnautica/GameLogic/Entities/Spawning/CrashFishBootstrapper.cs
I've added some tool tips to the launcher buttons etc.
=> Added tool tips to launcher

NitroxLauncher/Patching/PlatformDetection.cs
Hopefully somebody can test this with a discord installiation.
=> Fixed Platform detection for startup

NitroxLauncher/LaunchGamePage.xaml, NitroxLauncher/MainWindow.xaml, NitroxLauncher/MainWindow.xaml.cs, NitroxLauncher/ServerPage.xaml
Fixed button activation on the sidebar
moved Server Options text in server page in preparation of future additions
=> Revamped Look of the Nitrox Launcher

NitroxModel/Discovery/InstallationFinders/ConfigFileGameFinder.cs
Repeate PR due to accidental close from using master branch #801 
Added check to make sure that the config path within the config directory is valid. Fixes crash from having invalid directory in options menu
Ref issue #786
=> Added check for config valid game installation directory

.editorconfig, Nitrox.sln.DotSettings, NitroxLauncher/App.xaml.cs, NitroxLauncher/Events/ServerStartEventArgs.cs, NitroxLauncher/LaunchGamePage.xaml.cs, NitroxLauncher/LauncherLogic.cs, NitroxLauncher/MainWindow.xaml.cs, NitroxLauncher/NitroxLauncher.csproj, NitroxLauncher/OptionPage.xaml.cs, NitroxLauncher/Patching/NitroxEntryPatch.cs, NitroxLauncher/ServerConsolePage.xaml.cs, NitroxLauncher/ServerPage.xaml, NitroxLauncher/ServerPage.xaml.cs, NitroxLauncher/packages.config, NitroxModel/Discovery/GameInstallationFinder.cs, NitroxModel/Helper/PirateDetection.cs
Changes:
- Fixed checkbox items in server page not extended the full width of the checkbox.
- Removed .ini file check in PirateDetection because it'll trigger if Reshade is used. Fixes #816 
- Made PirateDetection event based.
- Changed the OpenFolderDialog to a dialog that is actually useable:
Did some general refactoring through the Launcher. Keeping features more focused to their class in addition to more sanity checking.
=> Refactor launcher

NitroxLauncher/LauncherLogic.cs, NitroxModel/Discovery/GameInstallationFinder.cs, NitroxModel/Discovery/IFindGameInstallation.cs, NitroxModel/Discovery/InstallationFinders/ConfigFileGameFinder.cs, NitroxModel/Discovery/InstallationFinders/EpicGamesRegistryFinder.cs, NitroxModel/Discovery/InstallationFinders/SteamGameRegistryFinder.cs, NitroxModel/Logger/Log.cs, NitroxServer/Serialization/World/WorldPersistence.cs, NitroxServer/Server.cs
- Changed log location to be Subnautica install directory for server if found
- Added logger name to log files to differentiate Server and Client logs
- Slightly reduced save log spam from server (should fix itself when server can hibernate if no players)
- Fixed exception in NitroxLauncher when it's trying to write command to server when Process.HasExited is true
=> Logs will now be put in one file for both server and client

NitroxClient/Communication/Packets/Processors/CyclopsActivateHornProcessor.cs
Fixed horn processor and changed range to 100-130 meters.
=> Fixing cyclops horn

NitroxClient/GameLogic/Spawning/DefaultEntitySpawner.cs, NitroxClient/MonoBehaviours/DiscordRP/DiscordController.cs, NitroxClient/MonoBehaviours/DiscordRP/DiscordJoinRequestGui.cs, NitroxClient/MonoBehaviours/Gui/MainMenu/JoinServer.cs, NitroxClient/MonoBehaviours/Gui/MainMenu/MainMenuMultiplayerPanel.cs, NitroxClient/MonoBehaviours/Gui/MainMenu/WarpToCommand.cs, NitroxPatcher/Patches/SubRoot_OnPlayerEntered_Patch.cs, NitroxServer/ConsoleCommands/Abstract/Command.cs, NitroxServer/IpLogger.cs, NitroxServer/Serialization/World/WorldPersistence.cs
More code but better than warning messages
=> Eliminated Warning Messages

NitroxClient/MonoBehaviours/Gui/MainMenu/MainMenuMods.cs
Because SP is broken anyway I opted to remove the button from the main menu until SP and Nitrox MP can coexist.
=> Removed the play button when nitrox is injected

NitroxClient/Communication/Packets/Processors/BedEnterProcessor.cs, NitroxClient/Communication/Packets/Processors/ConstructorBeginCraftingProcessor.cs, NitroxClient/Debuggers/SceneDebugger.cs, NitroxClient/GameLogic/InitialSync/BasePieceMetadataInitialSyncProcessor.cs, NitroxClient/MonoBehaviours/Gui/HUD/RemotePlayerVitals.cs, NitroxClient/NitroxClient.csproj, NitroxLauncher/MainWindow.xaml.cs, NitroxModel/Core/NitroxServiceLocator.cs, NitroxModel/DataStructures/GameLogic/BasePiece.cs, NitroxModel/DataStructures/GameLogic/VehicleModel.cs, NitroxModel/DataStructures/Optional.cs, NitroxModel/Logger/Log.cs, NitroxServer/Communication/Packets/Processors/DroppedItemPacketProcessor.cs, NitroxServer/Communication/Packets/Processors/SubRootChangedPacketProcessor.cs, NitroxTest/Client/Communication/DeferredPacketReceiverTest.cs, NitroxTest/Core/DependencyInjectionTests.cs, NitroxTest/Model/OptionalTest.cs, NitroxTest/Model/PacketProcessorTest.cs, NitroxTest/NitroxTest.csproj, NitroxTest/Patcher/Patches/BuilderPatchTest.cs
This allows Optional to be serialized by Protobuf and removes the abstract classes
Note: I Believe this might fix some base issues however that has yet to be tested. Testing requires PR #927 to be merged
=> Optional refactor

NitroxClient/GameLogic/ExosuitModuleEvent.cs, NitroxModel-Subnautica/Packets/ExosuitArmActionPacket.cs, NitroxModel/DataStructures/Optional.cs, NitroxPatcher/Patches/Dynamic/ExosuitGrapplingArm_OnHit_Patch.cs, NitroxTest/Model/OptionalTest.cs
Shouldve put this in previous PR...
=> OptionalTest updated for null changes

NitroxServer/GameLogic/Bases/BaseData.cs, NitroxServer/GameLogic/Entities/EntityData.cs, NitroxServer/GameLogic/EscapePodData.cs, NitroxServer/GameLogic/Items/InventoryData.cs, NitroxServer/GameLogic/Players/PlayerData.cs, NitroxServer/GameLogic/Unlockables/PDAStateData.cs, NitroxServer/GameLogic/Vehicles/VehicleData.cs
This should solve the issue of things being lost at deserialization
=> Refactored serializable classes

NitroxServer/ConsoleCommands/DayCommand.cs, NitroxServer/ConsoleCommands/DeopCommand.cs, NitroxServer/ConsoleCommands/ListCommand.cs, NitroxServer/ConsoleCommands/LoginCommand.cs, NitroxServer/ConsoleCommands/NightCommand.cs, NitroxServer/ConsoleCommands/SaveCommand.cs, NitroxServer/ConsoleCommands/WhisperCommand.cs
i noticed when you type help in the server command line
some commands had no description.
so i added some description to those one that were missing.
=> added description to some server commands

NitroxLauncher/LauncherLogic.cs, NitroxModel/Core/NitroxServiceLocator.cs
=> Fixed condition to show embedded server page

NitroxServer-Subnautica/ConsoleWindow.cs, NitroxServer-Subnautica/NitroxServer-Subnautica.csproj, NitroxServer-Subnautica/Program.cs
Fixes issues where server appears not be working due to console code waiting for edit mode to end.
=> Disabled quick edit when clicking in server console window

NitroxClient/GameLogic/InitialSync/BasePieceMetadataInitialSyncProcessor.cs, NitroxClient/GameLogic/InitialSync/EquippedItemInitialSyncProcessor.cs, NitroxClient/GameLogic/InitialSync/EscapePodInitialSyncProcessor.cs, NitroxClient/GameLogic/InitialSync/GlobalRootInitialSyncProcessor.cs, NitroxClient/GameLogic/InitialSync/InventoryItemsInitialSyncProcessor.cs, NitroxClient/GameLogic/InitialSync/PdaInitialSyncProcessor.cs, NitroxClient/GameLogic/InitialSync/PlayerInitialSyncProcessor.cs, NitroxClient/GameLogic/InitialSync/PlayerModulesInitialSyncProcessor.cs, NitroxClient/GameLogic/InitialSync/PlayerPositionInitialSyncProcessor.cs, NitroxClient/GameLogic/InitialSync/RemotePlayerInitialSyncProcessor.cs, NitroxClient/GameLogic/InitialSync/StorageSlotsInitialSyncProcessor.cs, NitroxClient/GameLogic/InitialSync/StoryGoalInitialSyncProcessor.cs, NitroxClient/GameLogic/InitialSync/VehicleInitialSyncProcessor.cs, NitroxLauncher/App.xaml.cs
See: https://stackoverflow.com/a/39269012/1277156
> Both yield return 0 and yield return null yields for a single frame. The biggest difference is that yield return 0 allocates memory because of boxing and unboxing of the 0 that happens under the hood, but yield return null does not allocate memory. Because of this, it is highly recommended to use yield return null if you care about performance.
=> No alloc yield

NitroxClient/Debuggers/BaseDebugger.cs, NitroxClient/Debuggers/EntityDebugger.cs, NitroxClient/Debuggers/SceneDebugger.cs, NitroxClient/MonoBehaviours/NitroxDebugManager.cs, NitroxClient/MonoBehaviours/NitroxEntity.cs, NitroxClient/NitroxClient.csproj
That was scary but looks like we have debug stuff now so yay
=> entity debugger and debug arrow

NitroxClient/Debuggers/EntityDebugger.cs, NitroxClient/Debuggers/SceneDebugger.cs
Lots of text and lots of boxes
=> Improved entity debugger

NitroxClient/MonoBehaviours/Gui/InGame/LostConnectionModal.cs, NitroxClient/MonoBehaviours/Gui/InGame/PlayerKickedModal.cs
Useless to keep that for now, justs add code complexity for a feature not really implemented yet
=> Remove rudimentary language feature for modals

NitroxLauncher/LauncherLogic.cs
https://www.reddit.com/r/subnautica/comments/a67m2c/subnautica_from_epic_games_store_force_launching/
=> Vrmode none

NitroxServer/GameLogic/PlayerManager.cs
Will Close depending on status of #986
=> PlayerStats Fix

NitroxLauncher/Pages/LaunchGamePage.xaml
Refined the contributor section after some feedback from the discord server with better line-height and font styling for easier readability
=> Improve: line-height of contributor list, wording and readability

NitroxLauncher/Pages/LaunchGamePage.xaml
@MarijnS95 this one is for you 😀
=> Fixed typo in Marijn's name

NitroxModel/DataStructures/Optional.cs, NitroxPatcher/NitroxPatcher.csproj, NitroxPatcher/Patches/Dynamic/Base_CopyFrom_Patch.cs, NitroxPatcher/Patches/Dynamic/Seamoth_SubConstructionComplete_Patch.cs
Bases Stay deleted now :D The parenting issue still exists however
=> Base fixes

NitroxClient/MonoBehaviours/Gui/MainMenu/JoinServer.cs, NitroxClient/MonoBehaviours/Gui/MainMenu/MainMenuMultiplayerPanel.cs
=> Message while trying to connect to localhost w/o server running

.github/workflows/buildingPullRequest.yml, .github/workflows/buildingRelease.yml, README.md
- Requested changes from https://github.com/SubnauticaNitrox/Nitrox/pull/1019
- Added `push` to BuildingRelease triggers
- Now two badges in README, one for release on for master
- Added license-badge
- Removed SN files from zipped release artifact
=> Update to workflow

NitroxClient/GameLogic/Vehicles.cs, NitroxModel/DataStructures/GameLogic/VehicleModel.cs, NitroxModel/DataStructures/Optional.cs, NitroxPatcher/Patches/Dynamic/CyclopsLightingPanel_OnSubConstructionComplete_Patch.cs
Tested that the lights keep their on/off state when rejoining.
=> Fix cyclops initsync

NitroxModel/MultiplayerSession/MultiplayerSessionReservationState.cs, NitroxModel/NitroxModel.csproj, NitroxModel/Packets/PlayerPermaDeathEvent.cs, NitroxServer/Communication/Packets/Processors/PlayerDeathEventProcessor.cs, NitroxServer/GameLogic/PlayerManager.cs, NitroxServer/GameLogic/Players/PlayerData.cs, NitroxServer/NitroxServer.csproj, NitroxServer/Player.cs
Adds perma death to any players who die during the game running on hardcore mode
Adds a message on player connect to reject any player who has previously died
=> Add hardcore perma death

.github/workflows/buildingPullRequest.yml, .github/workflows/buildingRelease.yml
Adds the submodule to the workflow pipelines to allow the checkout to get the litenetlib submodule
=> Fix workflows getting submodules submodule

NitroxPatcher/NitroxPatcher.csproj, NitroxPatcher/Patches/Persistent/UGUI_FeedbackCollector_IsEnabled_Patch.cs
Not sure a persistent patch is the best way to do this but the method is called before our dynamic patching is called
=> Added patch to remove feedback to developers

NitroxPatcher/Patches/Persistent/CellManager_TryLoadCacheBatchCells_Patch.cs, NitroxPatcher/TranspilerHelper.cs
Add additional transpiler helpers and refactor various patches to use them
=> Add additional Transpiler Helpers

AssemblyInfoCommon.cs
Bumps the version as not inline with release and stops the version update popup
=> Bumped Assembly version

.github/workflows/buildingPullRequest.yml, .github/workflows/buildingRelease.yml, README.md
- Making artifacts working again
- Removed Release badge because isn't working
=> Update to github actions

NitroxClient/GameLogic/Spawning/Metadata/PrecursorTeleporterMetadataProcessor.cs, NitroxClient/NitroxClient.csproj, NitroxModel/DataStructures/GameLogic/Entities/Metadata/EntityMetadata.cs, NitroxModel/DataStructures/GameLogic/Entities/Metadata/PrecursorTeleporterMetadata.cs, NitroxModel/NitroxModel.csproj, NitroxPatcher/NitroxPatcher.csproj, NitroxPatcher/Patches/Dynamic/PrecursorTeleporter_OnActivateTeleporter_Patch.cs
Sync currently isnt persistant as with other "doors"
=> Added precursor teleporer sync

NitroxLauncher/LauncherLogic.cs
Hope I did the submodule edit correctly now:
```bash
cd LiteNetLib
git checkout origin/0.8~1
cd ..
git commit -a -m "Reverted LiteNetLib to 0.8 branch"
```
=> Reset litenetlib submodule

NitroxClient/GameLogic/PlayerModel/PlayerModelManager.cs
Fixed color error when invoking uGUI_Pings OnColor method preventing remote players being visible
=> Fixed color error when invoking uGUI_Pings OnColor method

NitroxPatcher/NitroxPatcher.csproj, NitroxPatcher/Patches/Persistent/ScreenshotManager_Initialise.Path.cs
=> Added persistant patch for screenshot manager path

NitroxModel/Logger/Log.cs
=> Fix incorrects nlog archive files name

NitroxClient/GameLogic/InitialSync/PlayerInitialSyncProcessor.cs, NitroxModel/Packets/InitialPlayerSync.cs, NitroxModel/Server/ServerConfig.cs, NitroxModel/Server/ServerConfigItem.cs, NitroxModel/Server/ServerGameMode.cs, NitroxServer-Subnautica/App.config, NitroxServer-Subnautica/Program.cs, NitroxServer/Communication/Packets/Processors/PlayerDeathEventProcessor.cs, NitroxServer/GameLogic/PlayerManager.cs, NitroxServer/Serialization/World/World.cs, NitroxServer/Serialization/World/WorldPersistence.cs, NitroxServer/Server.cs
- Server gamemode wasn't transmitted to a player while joining a game
- Moved server log informations from WorldPersistence.cs to Server.cs
=> Fix gamemode transmission while joining a game

NitroxClient/GameLogic/Spawning/Metadata/PrecursorTeleporterActivationTerminalMetadataProcessor.cs, NitroxClient/GameLogic/Spawning/Metadata/PrecursorTeleporterMetadataProcessor.cs, NitroxClient/NitroxClient.csproj, NitroxModel/DataStructures/GameLogic/Entities/Metadata/EntityMetadata.cs, NitroxModel/DataStructures/GameLogic/Entities/Metadata/PrecursorTeleporterActivationTerminalMetadata.cs, NitroxModel/DataStructures/GameLogic/Entities/Metadata/PrecursorTeleporterMetadata.cs, NitroxModel/NitroxModel.csproj, NitroxPatcher/NitroxPatcher.csproj, NitroxPatcher/Patches/Dynamic/PrecursorKeyTerminalTrigger_OnTriggerEnter_Patch.cs, NitroxPatcher/Patches/Dynamic/PrecursorTeleporterActivationTerminal_OnProxyHandClick_Patch.cs
Fixed teleporter sync for both players and persistance
Added sync for the teleporter activation terminal
=> Fix teleporter sync

Directory.Build.props, Directory.Build.targets
Produced with the help of JR Alterra's Zoey
=> Clean up warnings

NitroxModel/Server/ServerConfig.cs
Changing value in the server config wasn't changing the value for the server
=> Fix FileSerializer in ServerConfig

NitroxClient/GameLogic/Spawning/Metadata/SealedDoorMetadataProcessor.cs
Fixes Sealed door syncing and reload 
Part fix for #1148
=> Fixed sealed door syncing

NitroxServer/Communication/Packets/Processors/EnergyMixinValueChangedPacketProcessor.cs
=> Removed unneeded debug logging

NitroxClient/GameLogic/Spawning/Metadata/StarshipDoorMetadataProcessor.cs, NitroxClient/GameLogic/Spawning/Metadata/WeldableWallPanelGenericMetadataProcessor.cs, NitroxClient/NitroxClient.csproj, NitroxModel/DataStructures/GameLogic/Entities/Metadata/EntityMetadata.cs, NitroxModel/DataStructures/GameLogic/Entities/Metadata/StarshipDoorMetadata.cs, NitroxModel/DataStructures/GameLogic/Entities/Metadata/WeldableWallPanelGenericMetadata.cs, NitroxModel/NitroxModel.csproj, NitroxPatcher/NitroxPatcher.csproj, NitroxPatcher/Patches/Dynamic/StarshipDoor_LockDoor_Patch.cs, NitroxPatcher/Patches/Dynamic/StarshipDoor_OnDoorToggle_Patch.cs, NitroxPatcher/Patches/Dynamic/StarshipDoor_UnlockDoor_Patch.cs, NitroxPatcher/Patches/Dynamic/WeldableWallPanelGeneric_UnlockDoor_Patch.cs
Resolves second part of #1148
Added weldable panel syncing
Added ondoortoggle to sync doors opening/closing and persistance
Also futureproofs the locking and unlocking of the starship doors
=> Add weldable door sync

NitroxServer/Communication/Packets/Processors/VehicleMovementPacketProcessor.cs
Quickfix serverside to update player location that we need to be accurate for teleportations, store death location, ...
=> Update player position server side while in vehicle

NitroxLauncher/LauncherLogic.cs, NitroxModel/Helper/WebHelper.cs
This will allow us to bump the assembly version before releasing without having the popup
=> Made versioning check more robust

AssemblyInfoCommon.cs
* Updated to the last version of Subnautica
* Added initial syncing of precursor teleporters
* Added initial syncing for precursor key terminals
* Added initial syncing for Neptune Rocket
* Added JSON file save format
* Drastically reduced the number of Nitrox mod files copied into the game directory
* Chat hint icon will now disappear after first use
* Added a folder to store "in game" screenshots (Nitrox Screenshots)
* Improved /warpto {player} command to /warp {player} [otherplayer]
* Improved battery values sync
* Fixed linux compatibility for servers
* Fixed a bug causing /list command to display weird things
* Fixed a bug where inventory items could be deleted on reload
* Fixed a bug where the server gamemode wasn't transmitted to the player while joining
* Fixed a bug where an …
=> Bump assembly version

NitroxPatcher/NitroxPatcher.csproj, NitroxPatcher/Patches/Dynamic/OnGoalUnlockTracker_NotifyGoalComplete_Patch.cs, NitroxServer/Communication/Packets/Processors/StoryEventSendProcessor.cs
Removes duplication of goals such as the aurora explosion
Readded a missing patch for the goals
Partly implements #1113
=> Fix story ping persistance

NitroxServer/GameLogic/EventTriggerer.cs, NitroxServer/GameLogic/PlayerManager.cs, NitroxServer/Server.cs
Added saving and reanable of events and server time when player disconnects/connects
Moved connection reanable to actually work as before would only work on second player connecting.
Resolves: #1235
=> Added the ability to pause server when all players disconnect

NitroxModel/Server/ServerConfig.cs
Resolves #1248
Thanks to @jar349 for highlighting the issue
=> Fix default port from 1100 to 11000

NitroxClient/MonoBehaviours/DiscordRP/DiscordRPController.cs, NitroxClient/MonoBehaviours/Multiplayer.cs, NitroxModel/Packets/MultiplayerSessionPolicy.cs, NitroxServer/Communication/Packets/Processors/MultiplayerSessionPolicyRequestProcessor.cs, NitroxTest/Client/Communication/MultiplayerSessionTests/ConnectionStateTests/ConnectionNegotiatingStateTests/EstablishingSessionPolicyStateTests.cs, NitroxTest/Client/Communication/MultiplayerSessionTests/TestConstants.cs
=> Enabled max discord party to be updated from max connections config

NitroxClient/GameLogic/Entities.cs
Fixed regression from missing logger import introduced in #1256
=> Added missing reference for error log

NitroxClient/MonoBehaviours/Gui/MainMenu/MainMenuMultiplayerPanel.cs
Worth noting does not support simplified IPv6 such as 2001:cdba::3257:9652
Thanks to @Measurity for the support with this regex
=> Added support for IPv6

NitroxClient/Communication/Packets/Processors/EscapePodChangedProcessor.cs, NitroxClient/GameLogic/EscapePodManager.cs, NitroxClient/GameLogic/InitialSync/EscapePodInitialSyncProcessor.cs, NitroxClient/GameLogic/InitialSync/RemotePlayerInitialSyncProcessor.cs, NitroxClient/GameLogic/LocalPlayer.cs, NitroxClient/GameLogic/RemotePlayer.cs, NitroxClient/NitroxClient.csproj, NitroxModel/NitroxModel.csproj, NitroxModel/Packets/EscapePodChanged.cs, NitroxPatcher/NitroxPatcher.csproj, NitroxPatcher/Patches/Dynamic/Player_SetCurrentEscapePod_Patch.cs, NitroxServer/Communication/Packets/Processors/EscapePodChangedPacketProcessor.cs, NitroxServer/NitroxServer.csproj
- Fixed the swim in subroot bug when joining a server.
- Fixed swim bug for escape pods when joining a server.
Fixed: #127
=> Fixed the swim in subroots bug when joining a server.

NitroxClient/Communication/Packets/Processors/RocketPreflightCompleteProcessor.cs, NitroxClient/Communication/Packets/Processors/RocketStageUpdateProcessor.cs, NitroxClient/GameLogic/Rockets.cs, NitroxClient/NitroxClient.csproj, NitroxModel-Subnautica/DataStructures/GameLogic/NeptuneRocketModel.cs, NitroxModel-Subnautica/NitroxModel-Subnautica.csproj, NitroxModel-Subnautica/Packets/RocketPreflightComplete.cs, NitroxModel-Subnautica/Packets/RocketStageUpdate.cs, NitroxPatcher/NitroxPatcher.csproj, NitroxPatcher/Patches/Dynamic/RocketConstructor_StartRocketConstruction_Patch.cs, NitroxPatcher/Patches/Dynamic/RocketPreflightCheckManager_CompletePreflightCheck_Patch.cs, NitroxPatcher/Patches/Dynamic/Rocket_ElevatorControlButtonActivate_Patch.cs, NitroxPatcher/Patches/Dynamic/Rocket_Start_Patch.cs, NitroxServer-Subnautica/Communication/Packets/Processors/RocketPreflightCompleteProcessor.cs, NitroxServer-Subnautica/NitroxServer-Subnautica.csproj
-  FIX : Buildbots are not sync when building rocket stages
-  FIX : Final rocket stage wasn't persist on reload
-  ADD : Sync and persistence for rocket preflights
=> Rocket improvements

NitroxClient/MonoBehaviours/Gui/MainMenu/JoinServer.cs, NitroxClient/MonoBehaviours/Gui/MainMenu/MainMenuNotification.cs, NitroxServer/Communication/Packets/Processors/MultiplayerSessionReservationRequestProcessor.cs
I tried to handle spaced usernames server-side in the first place, but looking back on it, was just adding unnecessary technical debt for a such simple thing. That's why I decided to forbid weird usernames beforehand
=> Adds username validation upon logging

NitroxClient/MonoBehaviours/DiscordRP/DiscordRPController.cs, NitroxClient/MonoBehaviours/Gui/MainMenu/MainMenuMultiplayerPanel.cs, NitroxClient/MonoBehaviours/Multiplayer.cs, NitroxPatcher/Main.cs
Reworked ipv4/ipv6 and domain logic.
Changed format of server file
=> Fixed connection via domain name

NitroxModel/Logger/Log.cs, NitroxServer-Subnautica/ConsoleWindow.cs, NitroxServer-Subnautica/Program.cs
Fixes issue where server closes too fast to see error.
=> Added unhandled exceptions handler on server

NitroxClient/MonoBehaviours/Gui/MainMenu/JoinServer.cs, NitroxModel/Packets/MultiplayerSessionPolicy.cs, NitroxServer/Communication/Packets/Processors/MultiplayerSessionPolicyRequestProcessor.cs, NitroxServer/Serialization/ServerConfig.cs, NitroxTest/Client/Communication/MultiplayerSessionTests/ConnectionStateTests/ConnectionNegotiatingStateTests/EstablishingSessionPolicyStateTests.cs, NitroxTest/Client/Communication/MultiplayerSessionTests/TestConstants.cs
Im almost certian that changes will be needed as im not 100% happy with the code myself BUT it does work as an implementation.
Feedback would be most welcome, haven't done any unity UI's before.
Resolves #1126
=> Added server password input when required

NitroxServer/Serialization/World/WorldPersistence.cs
Fixes the fun error of sunrunners directory when first loading
=> Changed error to warn without error log for non debug builds

NitroxModel/Serialization/PropertiesWriter.cs
- Added warn if property value is invalid. Falls back to default value.
=> Improved config validation if properties are invalid, falling back to default value

Directory.Build.props, Directory.Build.targets, NitroxModel/IsExternalInit.cs, NitroxModel/NitroxModel.csproj, NitroxModel/packages.config, NitroxServer-Subnautica/NitroxServer-Subnautica.csproj, NitroxServer-Subnautica/packages.config, NitroxServer/NitroxServer.csproj, NitroxServer/packages.config
Added dependencies and dummy classes where needed to support as many C# 9 features as possible.
=> Upgraded projects to C# 9

NitroxModel/Logger/Log.cs, NitroxModel/NitroxModel.csproj, NitroxModel/OS/FileSystem.cs, NitroxModel/OS/MacOS/MacFileSystem.cs, NitroxModel/OS/Unix/UnixFileSystem.cs, NitroxModel/OS/Windows/WinFileSystem.cs, NitroxServer-Subnautica/Program.cs
Changed opening of log file to use new FileSystem.cs API
=> Fixed regression that prevented log file from opening after exception occurred

NitroxLauncher/App.xaml.cs, NitroxLauncher/LauncherLogic.cs, NitroxLauncher/MainWindow.xaml.cs, NitroxLauncher/Pages/ServerConsolePage.xaml.cs, NitroxTest/NitroxTest.csproj
- Cleaned up how launcher closes. Asking users if they are sure when server is embedded.
- Removed double import in NitroxTest.csproj
=> Immediately hide launcher window when it is closing

Nitrox.sln.DotSettings, NitroxClient/MonoBehaviours/DiscordRP/DiscordRPController.cs, NitroxClient/MonoBehaviours/Gui/MainMenu/JoinServer.cs, NitroxClient/MonoBehaviours/Gui/MainMenu/MainMenuMods.cs, NitroxClient/MonoBehaviours/Gui/MainMenu/MainMenuMultiplayerPanel.cs, NitroxServer/Communication/NetworkingLayer/NitroxServer.cs
- Reduced load/reload time and freeze frame on button presses.
- Added caching for frequently used GameObjects, Transforms, etc.
- Fixed a potential bug in `NitroxServer.SetupUPNP()`
=> Updated MainMenu-UI

Nitrox.Subnautica.Assets/LanguageFiles/English.json, Nitrox.Subnautica.Assets/LanguageFiles/German.json, NitroxClient/Communication/Packets/Processors/InitialPlayerSyncProcessor.cs, NitroxClient/MonoBehaviours/Gui/InGame/LostConnectionModal.cs, NitroxClient/MonoBehaviours/Gui/InGame/PlayerKickedModal.cs, NitroxClient/MonoBehaviours/Gui/MainMenu/JoinServer.cs, NitroxClient/MonoBehaviours/Gui/MainMenu/LoadingScreenVersionText.cs, NitroxClient/MonoBehaviours/Gui/MainMenu/MainMenuMods.cs, NitroxClient/MonoBehaviours/Gui/MainMenu/MainMenuMultiplayerPanel.cs, NitroxClient/MonoBehaviours/Gui/MainMenu/MainMenuNotification.cs, NitroxClient/MonoBehaviours/Multiplayer.cs, NitroxLauncher/NitroxLauncher.csproj, NitroxPatcher/NitroxPatcher.csproj, NitroxPatcher/Patches/Persistent/Language_LoadLanguageFile_Patch.cs
Starting with English (as default) and German
=> Added support for translation

NitroxServer/Communication/NetworkingLayer/NitroxServer.cs
Gives users a better message as conflicts can likely be ignored due to the server already creating a mapping before
=> Added message for automatic port conflict

NitroxServer/Serialization/World/WorldPersistence.cs
EntityData was not being added in backup zip
=> Added EntityData.nitrox to zip backup

Nitrox.Subnautica.Assets/LanguageFiles/Italian.json
I've added initial translations for italian language
=> Added italian translation

NitroxServer/GameLogic/GameData.cs, NitroxServer/GameLogic/StoryTimingData.cs, NitroxServer/Serialization/World/PersistedWorldData.cs
=> Fixed StoryTimingData and Seed from resetting

NitroxTest/Serialization/WorldPersistenceTest.cs
Fixes the seed persistence
Paused timers to stop time passing between worldData and afterWorldData
=> Fixed world persistance tests

NitroxLauncher/LauncherLogic.cs, NitroxLauncher/MainWindow.xaml.cs, NitroxLauncher/NitroxLauncher.csproj, NitroxLauncher/Pages/OptionPage.xaml.cs, NitroxLauncher/Patching/AppHelper.cs, NitroxModel/Discovery/GameInstallationFinder.cs, NitroxModel/Discovery/IFindGameInstallation.cs, NitroxModel/Discovery/InstallationFinders/ConfigFileGameFinder.cs, NitroxModel/Discovery/InstallationFinders/EpicGamesInstallationFinder.cs, NitroxModel/Discovery/InstallationFinders/GameInCurrentDirectoryFinder.cs, NitroxModel/Discovery/InstallationFinders/SteamGameRegistryFinder.cs, NitroxModel/Discovery/Models/Platform.cs, NitroxModel/Discovery/PlatformDetection.cs, NitroxModel/NitroxModel.csproj
* Moved the detection to NitroxModel
* Introduced the "Platform" Enum in order to figure out which platform we are dealing with
* Cleaned up LauncherLogic.cs  a bit so it can be more readable
=> Refactor PlatformDetection inside Launcher

.github/workflows/buildingPullRequest.yml, .github/workflows/buildingRelease.yml
Ignores changes to only the PirateDetection.cs file so no artifacts are built
=> Added checks to workflow

Nitrox.Bootloader/Main.cs, NitroxLauncher/LauncherLogic.cs, NitroxLauncher/NitroxLauncher.csproj, NitroxLauncher/Patching/QModHelper.cs
Stop qmod initialisation on load and restore on exit
=> Enable loading multiplayer with QMod installed

NitroxClient/Communication/Packets/Processors/PDAScannerEntryProgressProcessor.cs
Looking through logs and found this small spelling error so cleaned it up. Also added a little more information to the log so its a little more meaningful.
=> Fix spelling pda scanner entry progress

NitroxPatcher/NitroxPatcher.csproj, NitroxPatcher/Patches/Dynamic/Bench_ExitSittingMode_Patch.cs, NitroxPatcher/Patches/Dynamic/Bench_OnHandClick_Patch.cs, NitroxPatcher/Patches/Dynamic/Bench_OnPlayerDeath_Patch.cs
=> Fixed more than one player using a Bench/Chair

NitroxModel/Serialization/NitroxConfig.cs, NitroxServer-Subnautica/Program.cs, NitroxServer/ConsoleCommands/AutosaveCommand.cs, NitroxServer/ConsoleCommands/ChangeAdminPasswordCommand.cs, NitroxServer/ConsoleCommands/ChangeServerGamemodeCommand.cs, NitroxServer/ConsoleCommands/ChangeServerPasswordCommand.cs, NitroxServer/ConsoleCommands/ConfigCommand.cs, NitroxServer/ConsoleCommands/SwapSerializerCommand.cs, NitroxServer/Serialization/ServerConfig.cs, NitroxServer/Server.cs, NitroxServer/ServerAutoFacRegistrar.cs
=> Refactored ServerConfig to serialize and deserialize the same instance

NitroxServer/ConsoleCommands/UpgradeCommand.cs, NitroxServer/GameLogic/Players/PersistedPlayerData.cs, NitroxServer/NitroxServer.csproj, NitroxServer/Serialization/SaveDataUpgrades/SaveDataUpgrade.cs, NitroxServer/Serialization/SaveDataUpgrades/Upgrade_V1500.cs
Added script for upgrading save files from V1.4.0.0 to V1.5.0.0 as good as possible.
=> Upgrade script V1.5.0.0

NitroxClient/MonoBehaviours/Gui/MainMenu/JoinServer.cs
Fix the color indicator at the bottom left that was set at blue by default
DOES NOT FIX COLOR IN GAME
=> Fix color UI inside MainMenu

NitroxClient/Communication/Packets/Processors/GhostCrafterBeginCraftingProcessor.cs, NitroxClient/Communication/Packets/Processors/GhostCrafterItemPickupProcessor.cs, NitroxClient/Communication/Packets/Processors/TimeChangeProcessor.cs, NitroxClient/GameLogic/Crafting.cs, NitroxModel/Packets/GhostCrafterBeginCrafting.cs, NitroxModel/Packets/GhostCrafterItemPickup.cs, NitroxModel/Packets/PickupItem.cs, NitroxModel/Packets/TimeChange.cs, NitroxPatcher/Patches/Dynamic/GhostCrafter_OnCraftingBegin_Patch.cs, NitroxServer/Communication/Packets/Processors/PlayerJoiningMultiplayerSessionProcessor.cs, NitroxServer/GameLogic/EventTriggerer.cs, NitroxServer/GameLogic/TimeKeeper.cs, NitroxServer/Serialization/World/VersionMismatchException.cs, NitroxServer/Serialization/World/WorldPersistence.cs, NitroxServer/Server.cs
* Some basic refactor to lighten the code
* Time will now be resync for everyone on player rejoin (We might need to implement a cron resync system for those kind of data from the server)
* Refactored TimeKeeper to match hardcoded value from subnautica (also switched from float to double, since we can deal with big numbers, and subnautica is internaly using double instead of float)
* Fix for the fabricator/workbench looping bug
* Fix for single use mobile vehicle bay bug
* Fix for pda journal starting at -5 causing multiple bugs
=> Fix for fabricator looping bug

Nitrox.sln.DotSettings, NitroxClient/GameLogic/Containers/PlantableContainerAddItemPostProcessor.cs, NitroxClient/GameLogic/InitialSync/InventoryItemsInitialSyncProcessor.cs, NitroxModel/DataStructures/GameLogic/NitroxColor.cs
Fix for plantables (and probably other items as well) not adding to their item-container.
=> Fix for plantables not adding to container

NitroxClient/MonoBehaviours/Gui/MainMenu/MainMenuMultiplayerPanel.cs, NitroxModel/Helper/NitroxAppData.cs, NitroxModel/Helper/Validate.cs, NitroxModel/NitroxModel.csproj, NitroxModel/OS/FileSystem.cs, NitroxModel/Serialization/ServerList.cs
Code for moving servers file:
https://github.com/SubnauticaNitrox/Nitrox/pull/1531/files#diff-3e79ff7d448e24c0bcab15fec82aa7cd292b05f94f7c5937c8d81e554d1f97c1R33-R37
=> Moved server list handling to separate class and moved file out of Subnautica folder

NitroxModel/Serialization/NitroxConfig.cs, NitroxServer/Serialization/ServerConfig.cs, NitroxServer/Server.cs
Removed serialize from save due to it being created on load.
Switched out deserialize for Update as it calls deserialize for us
=> Allows cfg to be updated with any changes rather than always using default properties for those missing

NitroxServer/GameLogic/Items/InventoryManager.cs
Switches from using container id to item id as to not overide the whole container and just modify the item
=> Fixed modules not saving correctly due to using containerid

NitroxModel/Helper/WebHelper.cs
Prevents a github tag causing an upgrade notification before we have released on website
=> Switched version check to website rather than github

NitroxServer/Communication/Packets/Processors/RadioPlayPendingMessageProcessor.cs, NitroxServer/GameLogic/Unlockables/StoryGoalData.cs
Concerning [Issue #1368](https://github.com/SubnauticaNitrox/Nitrox/issues/1368)
=> Added logging for Radio bug ArgumentOutOfRangeException

NitroxClient/GameLogic/Spawning/DefaultEntitySpawner.cs
Seems to fix https://github.com/SubnauticaNitrox/Nitrox/issues/1468
=> Spawning code race condition fix.

NitroxModel/GameInfo.cs, NitroxModel/NitroxModel.csproj
Will use this later in all other parts of the code instead of hard coding these numbers everywhere.
=> Added gameinfo class with info about SN1 and BZ

NitroxClient/MonoBehaviours/Gui/MainMenu/JoinServer.cs, NitroxClient/MonoBehaviours/Gui/MainMenu/MainMenuMultiplayerPanel.cs, NitroxPatcher/NitroxPatcher.csproj, NitroxPatcher/Patches/Persistent/MainMenuRightSide_OpenGroup_Patch.cs
Concerning [Issue#1640](https://github.com/SubnauticaNitrox/Nitrox/issues/1640)
=> Fix the: tab switch when in join menu breaks multiplayer (#1640)

NitroxClient/MonoBehaviours/Gui/MainMenu/JoinServer.cs, NitroxPatcher/Patches/Persistent/MainMenuRightSide_OpenGroup_Patch.cs
Little modification of ServerJoinMenu
=> Fix tab switch after join menu modification

NitroxServer/Communication/NitroxServer.cs
Added a disclaimer to the UPNP warning message stating that if using manual portfowarding or Hamachi, you should disregard the warning for easier user comprehension.
=> Added disclaimer to the UPNP warning message.

NitroxServer/GameLogic/Entities/EntityData.cs
Local position should never be changed
=> Fixes the issue of entities not respawning at each server restart

NitroxClient/MonoBehaviours/NitroxEntity.cs
This theoretically should help with some pointless log spam
=> Add OnEnable and OnDisable to NitroxEntity

NitroxLauncher/LauncherLogic.cs, NitroxModel/Platforms/OS/Shared/FileSystem.cs
The old check was a hassle on the users end if nothing was necessary to change
=> adjusted permission check

NitroxClient/ClientAutoFacRegistrar.cs, NitroxClient/Communication/Abstract/IPacketSender.cs, NitroxClient/Communication/MultiplayerSession/MultiplayerSessionManager.cs, NitroxClient/Communication/Packets/Processors/VehicleColorChangeProcessor.cs, NitroxClient/Communication/Packets/Processors/VehicleNameChangeProcessor.cs, NitroxClient/Communication/Packets/Processors/VehicleUndockingProcessor.cs, NitroxClient/Helpers/ThrottledPacketSender.cs, NitroxClient/MonoBehaviours/Multiplayer.cs, NitroxClient/NitroxClient.csproj, NitroxClient/Unity/Helper/GameObjectHelper.cs, NitroxModel/Packets/VehicleColorChange.cs, NitroxModel/Packets/VehicleNameChange.cs, NitroxPatcher/Patches/Dynamic/SubNameInput_OnColorChange_Patch.cs, NitroxPatcher/Patches/Dynamic/SubNameInput_OnNameChange_Patch.cs, NitroxServer/Communication/Packets/Processors/VehicleColorChangeProcessor.cs, NitroxServer/Communication/Packets/Processors/VehicleNameChangeProcessor.cs
Seamoth and exosuit had some update issues between games while updated.
I tested all my change to be sure that color and name are properly updated on: seamoth, exosuit, cyclops and rocket.
Fix #1470
Fix #1524
=> Fixed vehicles color and name synchronisation

NitroxPatcher/Patches/Dynamic/EnergyMixin_ModifyCharge_Patch.cs
This changes fixes the fast flashlight battery discharge.
=> Fixes the fast flashlight battery discharge

Nitrox.Subnautica.Assets/LanguageFiles/Danish.json
Added a Danish language option. I think it's pretty well translated but you never know when you will find a better synonym for something.
Really great mod though!
=> Danish localization 

NitroxLauncher/App.config, NitroxLauncher/App.xaml, NitroxLauncher/LauncherConfig.cs, NitroxLauncher/LauncherLogic.cs, NitroxLauncher/LauncherNotifier.cs, NitroxLauncher/Pages/LaunchGamePage.xaml, NitroxLauncher/Pages/LaunchGamePage.xaml.cs, NitroxLauncher/Pages/OptionPage.xaml, NitroxLauncher/Pages/OptionPage.xaml.cs, NitroxLauncher/Pages/ServerPage.xaml.cs, NitroxLauncher/Pages/UpdatePage.xaml, NitroxLauncher/Properties/Settings.Designer.cs, NitroxLauncher/Properties/Settings.settings, NitroxModel/Platforms/Store/Discord.cs, NitroxModel/Platforms/Store/Egs.cs, NitroxModel/Platforms/Store/MSStore.cs, NitroxModel/Platforms/Store/Steam.cs
=> Added UI for custom launch arguments

NitroxServer/Server.cs
=> Realigned summary lines

NitroxServer/ConsoleCommands/Abstract/Command.cs, NitroxServer/ConsoleCommands/Abstract/Parameter.cs, NitroxServer/ConsoleCommands/Abstract/Type/TypeBoolean.cs, NitroxServer/ConsoleCommands/Abstract/Type/TypeEnum.cs, NitroxServer/ConsoleCommands/Abstract/Type/TypeFloat.cs, NitroxServer/ConsoleCommands/Abstract/Type/TypeInt.cs, NitroxServer/ConsoleCommands/Abstract/Type/TypePlayer.cs, NitroxServer/ConsoleCommands/Abstract/Type/TypeString.cs, NitroxServer/ConsoleCommands/AutosaveCommand.cs, NitroxServer/ConsoleCommands/BroadcastCommand.cs, NitroxServer/ConsoleCommands/ChangeAdminPasswordCommand.cs, NitroxServer/ConsoleCommands/ChangeServerGamemodeCommand.cs, NitroxServer/ConsoleCommands/ChangeServerPasswordCommand.cs, NitroxServer/ConsoleCommands/DeopCommand.cs, NitroxServer/ConsoleCommands/HelpCommand.cs, NitroxServer/ConsoleCommands/KickCommand.cs, NitroxServer/ConsoleCommands/LoadBatchCommand.cs, NitroxServer/ConsoleCommands/LoginCommand.cs, NitroxServer/ConsoleCommands/OpCommand.cs, NitroxServer/ConsoleCommands/PromoteCommand.cs, NitroxServer/ConsoleCommands/SwapSerializerCommand.cs, NitroxServer/ConsoleCommands/TeleportCommand.cs, NitroxServer/ConsoleCommands/TimeCommand.cs, NitroxServer/ConsoleCommands/WarpCommand.cs, NitroxServer/ConsoleCommands/WhisperCommand.cs, NitroxServer/ConsoleCommands/WhoisCommand.cs
Cant reopen the old pr due to rebase, pr for reference: [1562](https://github.com/SubnauticaNitrox/Nitrox/pull/1562)
Resolves #1574
=> Additional help information

NitroxClient/GameLogic/Cyclops.cs
=> Fix decoy launch button cooldown not applying

NitroxClient/GameLogic/Spawning/Metadata/EntitySignMetadataProcessor.cs, NitroxModel/DataStructures/GameLogic/Buildings/Metadata/SignMetadata.cs, NitroxModel/DataStructures/GameLogic/Entities/Metadata/EntityMetadata.cs, NitroxModel/DataStructures/GameLogic/Entities/Metadata/EntitySignMetadata.cs, NitroxPatcher/Patches/Dynamic/uGUI_SignInput_OnDeselect_Patch.cs
=> Fix lockers label disappearing

NitroxLauncher/Models/NitroxBlog.cs
=> Fixed character encoding for blog titles

NitroxPatcher/Patches/Dynamic/uGUI_SignInput_OnDeselect_Patch.cs
=> Fix a Sign metadata case that wasn't treated

NitroxModel/MultiplayerSession/MultiplayerSessionReservationState.cs, NitroxServer/GameLogic/PlayerManager.cs
This check is only client side for now, which can be problematic with evil persons
=> Added server check for invalid username

NitroxClient/Communication/MultiplayerSession/ConnectionState/AwaitingSessionReservation.cs, NitroxClient/Communication/MultiplayerSession/ConnectionState/EstablishingSessionPolicy.cs, NitroxClient/Communication/Packets/Processors/MedicalCabinetClickedProcessor.cs, NitroxClient/Communication/Packets/Processors/PlayFMODCustomEmitterProcessor.cs, NitroxClient/Communication/Packets/Processors/PlayFMODCustomLoopingEmitterProcessor.cs, NitroxClient/Communication/Packets/Processors/PlayFMODStudioEventEmitterProcessor.cs, NitroxClient/GameLogic/EscapePodManager.cs, NitroxClient/Resources/soundsWhitelist.csv, NitroxClient/Unity/Helper/GameObjectHelper.cs, NitroxModel/Helper/CallerArgumentExpressionAttribute.cs, NitroxModel/Helper/Validate.cs, NitroxModel/Serialization/ServerList.cs
This changes are/will be kind of a botch because we need them quickly for V1.6.0.0
=> Fixes for sound errors from RC3

NitroxServer-Subnautica/Program.cs
=> Prevent Ctrl+C from closing the server

Nitrox.Test/Patcher/Patches/Language_LoadLanguageFile_PatchTest.cs, Nitrox.Test/Serialization/WorldPersistenceTest.cs, Nitrox.Test/Server/GameLogic/EventTriggererTest.cs, NitroxServer-Subnautica/GameLogic/Entities/Spawning/CrashFishBootstrapper.cs, NitroxServer-Subnautica/GameLogic/Entities/Spawning/ReefbackBootstrapper.cs, NitroxServer-Subnautica/GameLogic/Entities/Spawning/UntypedCellEntityBootstrapper.cs, NitroxServer/Communication/Packets/Processors/PlayerJoiningMultiplayerSessionProcessor.cs, NitroxServer/GameLogic/Entities/Spawning/BatchEntitySpawner.cs, NitroxServer/GameLogic/Entities/Spawning/IEntityBootstrapper.cs, NitroxServer/GameLogic/EventTriggerer.cs, NitroxServer/Helper/DeterministicGenerator.cs, NitroxServer/Serialization/World/WorldPersistence.cs, NitroxServer/Server.cs
=> Making AuroraExplosion seed based

NitroxServer/ConsoleCommands/SummaryCommand.cs, NitroxServer/Server.cs
=> Removed save location from summary if requested by player

.github/ISSUE_TEMPLATE/bug_report.yaml
`On which platform did you bought Subnautica?`
to
`On which platform did you buy Subnautica?`
=> Fixed typo in bug_report.yaml

NitroxServer/ConsoleCommands/MuteCommand.cs, NitroxServer/ConsoleCommands/UnmuteCommand.cs
We could use true/false in the packet instantiations but anyway
=> Updates local state of muted player if it's not synced with server in case of desync

Nitrox.Assets.Subnautica/Nitrox.Assets.Subnautica.shproj, NitroxLauncher/Pages/ServerPage.xaml, NitroxLauncher/Pages/ServerPage.xaml.cs
- [Fixing variable access error in launcher](https://github.com/SubnauticaNitrox/Nitrox/commit/66d9b821cecaf8a4156294843937dec5296d5312)
- [Fixing warning of framework version mismatch](https://github.com/SubnauticaNitrox/Nitrox/commit/0b14e953132acb0c4745d9fe9e7e2eb8a8d8fd54)
=> Fixing built up IDE errors and warnings

Nitrox.Assets.Subnautica/LanguageFiles/en.json, NitroxClient/MonoBehaviours/Discord/DiscordClient.cs, NitroxModel/Helper/NitroxUser.cs
* Added more logging to see the exact workflow in the log
* Fixed 3 NRE polluting logs when discord is not launched or if you don't have subnautica on steam
=> Fix some discord client NRE

NitroxModel/Platforms/Store/Steam.cs
Steam sometimes isn't ready just after the PID for its process is set. Added a second delay for Steam to be truly ready.
=> Fixed steam sometimes not starting Subnautica

NitroxLauncher/Models/WpfControlHelper.cs, NitroxLauncher/Pages/ServerPage.xaml, NitroxLauncher/Pages/ServerPage.xaml.cs, NitroxServer/Serialization/World/WorldManager.cs, NitroxServer/Server.cs
Used `ItemsControl` instead of `ListView`. The former does not have a `SelectedIndex` so I refactored it to use `DataContext` from the sender of the control events.
=> Fixed world list not focusing correctly on the items

Nitrox.Test/Model/DataStructures/NitroxIdTest.cs, NitroxClient/GameLogic/EscapePodManager.cs, NitroxClient/GameLogic/InitialSync/InventoryItemsInitialSyncProcessor.cs, NitroxClient/MonoBehaviours/ThrottledBuilder.cs, NitroxModel/DataStructures/NitroxId.cs, NitroxServer/GameLogic/Bases/BaseManager.cs, NitroxServer/GameLogic/EscapePodManager.cs, NitroxServer/Player.cs
https://github.com/SubnauticaNitrox/Nitrox/issues/1903
=> Fix for base pieces failing to be removed on server (#1903)

Nitrox.BuildTool/Program.cs, Nitrox.BuildTool/Publicizer.cs
=> Cleaned up publicizer code, reducing allocations

NitroxPatcher/Patches/Dynamic/uGUI_Pings_OnLateUpdate_Patch.cs
This reverts commit 3c298fff1ed25b9a5d1902d0d40bb3c3f67fefca.
=> Revert "Changed OnLateUpdate to UpdatePings (#1913)"

NitroxClient/Debuggers/Drawer/Unity/ColorDrawer.cs, NitroxClient/MonoBehaviours/Gui/MainMenu/JoinServer.cs, NitroxClient/MonoBehaviours/Gui/MainMenu/JoinServerJoinWindow.cs, NitroxClient/MonoBehaviours/Gui/MainMenu/JoinServerServerList.cs
Splits the JoinServer logic and ui manipulation into different files
Fixes color picker being smaller as before the SN update (by a factor of 5).
=> Refactored JoinServer logic

NitroxClient/Debuggers/BaseDebugger.cs, NitroxClient/Debuggers/NetworkDebugger.cs, NitroxClient/Debuggers/SceneExtraDebugger.cs, NitroxClient/Debuggers/SoundDebugger.cs
Subnautica 2.0 introduced this issue, just rearranged the sizes of the debuggers
=> Fix debuggers size

NitroxServer-Subnautica/Program.cs
**Test**
1. Run both server/client, in any order, at the same time. Should start without issue (that isn't already known ☜(ﾟヮﾟ☜)).
=> Changed how files are read, allowing multiple readers

Nitrox.Test/Server/Serialization/WorldPersistenceTest.cs, Nitrox.sln.DotSettings, NitroxClient/GameLogic/Spawning/WorldEntities/DefaultWorldEntitySpawner.cs, NitroxClient/GameLogic/Spawning/WorldEntities/PlaceholderGroupWorldEntitySpawner.cs, NitroxClient/GameLogic/Spawning/WorldEntities/WorldEntitySpawnerResolver.cs, NitroxModel/DataStructures/GameLogic/Entities/PlaceholderGroupWorldEntity.cs, NitroxModel/DataStructures/GameLogic/Entities/PrefabPlaceholderEntity.cs, NitroxModel/DataStructures/GameLogic/Entities/WorldEntity.cs, NitroxModel/DataStructures/GameLogic/Entity.cs, NitroxServer-Subnautica/Resources/Parsers/PrefabPlaceholderGroupsParser.cs, NitroxServer/GameLogic/Entities/Spawning/BatchEntitySpawner.cs, NitroxServer/Resources/PrefabPlaceholderAsset.cs, NitroxServer/Resources/PrefabPlaceholdersGroupAsset.cs
This fixes EntitySlots (=> all random spawned loot and fragments) not spawning
~~I am not happy how `PlaceholderGroupWorldEntity` turned out. Feedback is appreciated, espacially since the current solution is not working with ProtoBuf (bc null).~~
=> Fix EntitySlots spawning

Nitrox.BuildTool/Program.cs
I thought about adding git check if current branch is on master (something like `git merge-base --is-ancestor master HEAD`). But since this code didn't exist before there's probably no need.
Tested that build tool works unchanged when on latest Subnautica code.
=> Added error in BuildTool when targeting Subnautica legacy branch

Nitrox.Test/Patcher/PatchTestHelper.cs, Nitrox.Test/Patcher/Patches/Dynamic/DevConsole_Update_PatchTest.cs, Nitrox.Test/Patcher/Patches/Dynamic/uSkyManager_SetVaryingMaterialProperties_PatchTest.cs, NitroxPatcher/Patches/Dynamic/BreakableResource_SpawnResourceFromPrefab_Patch.cs, NitroxPatcher/Patches/Dynamic/DevConsole_Update_Patch.cs, NitroxPatcher/Patches/Dynamic/ItemsContainer_DestroyItem_Patch.cs, NitroxPatcher/Patches/Dynamic/SpawnOnKill_OnKill_Patch.cs, NitroxPatcher/Patches/Dynamic/uSkyManager_SetVaryingMaterialProperties_Patch.cs, NitroxPatcher/PatternMatching/ILExtensions.cs
=> Added common usage extension methods for IL pattern matching

.github/ISSUE_TEMPLATE/bug_report.yaml
=> bug_report.yml: fix typo

.github/ISSUE_TEMPLATE/bug_report.yaml
Change Operation System to Operating System
Change "How did it happened?" to "How did it happen?"
=> bug_report.yaml: fix two typos

Nitrox.Test/Client/Communication/DeferredPacketReceiverTest.cs, NitroxClient/Communication/NetworkingLayer/LiteNetLib/LiteNetLibClient.cs, NitroxClient/Communication/PacketReceiver.cs, NitroxClient/MonoBehaviours/Multiplayer.cs, NitroxModel/NitroxModel.csproj
Note the amount sent and total size:
Previously:
Now:
=> Updated binarypack and reduced packet receive memory allocation

NitroxClient/Communication/NetworkingLayer/LiteNetLib/LiteNetLibClient.cs, NitroxClient/Communication/Packets/Processors/PlayerCinematicControllerCallProcessor.cs, NitroxClient/Communication/Packets/Processors/PlayerKickedProcessor.cs, NitroxClient/Communication/Packets/Processors/ServerStoppedProcessor.cs, NitroxClient/GameLogic/HUD/PdaTabs/uGUI_PlayerPingEntry.cs, NitroxClient/GameLogic/Spawning/WorldEntities/EscapePodWorldEntitySpawner.cs, NitroxClient/GameLogic/Spawning/WorldEntities/VehicleWorldEntitySpawner.cs, NitroxClient/MonoBehaviours/CinematicController/MultiplayerCinematicController.cs, NitroxClient/MonoBehaviours/CinematicController/MultiplayerCinematicReference.cs, NitroxClient/MonoBehaviours/CinematicController/RemotePlayerCinematicController.cs, NitroxClient/MonoBehaviours/Gui/HUD/DenyOwnershipHand.cs, NitroxClient/MonoBehaviours/Gui/Modals/ConfirmModal.cs, NitroxClient/MonoBehaviours/Gui/Modals/KickedModal.cs, NitroxClient/MonoBehaviours/Gui/Modals/LostConnectionModal.cs, NitroxClient/MonoBehaviours/Gui/Modals/Modal.cs, NitroxClient/MonoBehaviours/Gui/Modals/ServerStoppedModal.cs, NitroxPatcher/Patches/Dynamic/Bench_OnHandClick_Patch.cs, NitroxPatcher/Patches/Dynamic/Incubator_OnHandClick_Patch.cs, NitroxPatcher/Patches/Dynamic/IngameMenu_OnDeselect_Patch.cs, NitroxPatcher/Patches/Dynamic/PilotingChair_OnHandClick_Patch.cs, NitroxPatcher/Patches/Dynamic/PlayerCinematicController_OnPlayerCinematicModeEnd_Patch.cs, NitroxPatcher/Patches/Dynamic/PlayerCinematicController_StartCinematicMode_Patch.cs, NitroxPatcher/Patches/Dynamic/PlayerCinematicController_Start_Patch.cs, NitroxPatcher/Patches/Dynamic/PropulsionCannon_GrabObject_Patch.cs, NitroxPatcher/Patches/Dynamic/Vehicle_OnHandClick_Patch.cs
Adds translation for DenyOwnershipHand 
Moves a few GUI files to the right place and adjusts namespaces
=> Add DenyOwnershipHand translation and refactor few MBs namespaces

NitroxClient/Communication/Packets/Processors/DiscordRequestIPProcessor.cs, NitroxServer/Communication/Packets/Processors/DiscordRequestIPProcessor.cs
=> Standardises Discord IP Getters to match LogHowToConnectAsync

NitroxPatcher/Patches/Persistent/GameAnalytics_Patch.cs
=> Suppress AnalyticsController to avoid NRE

Nitrox.Test/Server/Serialization/WorldPersistenceTest.cs, NitroxClient/GameLogic/InitialSync/StoryGoalInitialSyncProcessor.cs, NitroxModel/DataStructures/GameLogic/InitialStoryGoalData.cs, NitroxPatcher/Patches/Dynamic/CrashedShipExploder_Update_Patch.cs, NitroxPatcher/Patches/Dynamic/StoryGoalScheduler_Schedule_Patch.cs, NitroxServer/Communication/Packets/Processors/StoryGoalExecutedProcessor.cs, NitroxServer/GameLogic/Unlockables/StoryGoalData.cs, NitroxServer/Server.cs
=> Fix beacons not reappearing after reconnecting

NitroxClient/GameLogic/InitialSync/StoryGoalInitialSyncProcessor.cs, NitroxPatcher/Patches/Dynamic/AuroraWarnings_Update_Patch.cs
To test, start a world. You no longer get aurora warning 4 on connection :)
=> Fix aurora warnings on connection

NitroxClient/GameLogic/Spawning/WorldEntities/DefaultWorldEntitySpawner.cs
=> Fix objects spawning ignoring ClassId because of TechType cached prefab

Nitrox.Launcher/Views/LaunchGameView.axaml
The contributors section should probably show my real username :)
=> Update contributors list

Nitrox.Launcher/Models/Converters/IsTypeConverter.cs, Nitrox.Launcher/Models/Extensions/MessageReceiverExtensions.cs, Nitrox.Launcher/Models/Extensions/ScreenExtensions.cs, Nitrox.Launcher/Models/IMessageReceiver.cs, Nitrox.Launcher/Models/Services/ServerService.cs, Nitrox.Launcher/ViewModels/Abstract/ViewModelBase.cs, Nitrox.Launcher/ViewModels/EmbeddedServerViewModel.cs, Nitrox.Launcher/ViewModels/LaunchGameViewModel.cs, Nitrox.Launcher/ViewModels/MainWindowViewModel.cs, Nitrox.Launcher/ViewModels/ManageServerViewModel.cs, Nitrox.Launcher/ViewModels/ServersViewModel.cs, Nitrox.Launcher/Views/MainWindow.axaml, Nitrox.Launcher/Views/ServersView.axaml, NitroxModel/Helper/NatHelper.cs, NitroxModel/Platforms/OS/Windows/RegistryEx.cs, NitroxModel/Platforms/Store/Discord.cs, NitroxModel/Platforms/Store/MSStore.cs, NitroxModel/Platforms/Store/Steam.cs, NitroxServer-Subnautica/Program.cs
First 3 commits already reviewed here:
- #2277
=> Launcher bug fixing

NitroxPatcher/Patches/Dynamic/CyclopsDestructionEvent_SpawnLootAsync_Patch.cs
=> Fix patch callback function being treated as Prefix

NitroxModel/DataStructures/GameLogic/AbsoluteEntityCell.cs, NitroxModel/Helper/Matrix4x4Extension.cs, NitroxServer/GameLogic/Entities/EntityData.cs
=> Fix OverflowException in AbsoluteEntityCell with teleporting entity to origin

Nitrox.Launcher/ViewModels/LaunchGameViewModel.cs
=> Fix MS Store not receiving nitrox custom arguments launch

NitroxModel/Platforms/Store/MSStore.cs, NitroxPatcher/Main.cs
=> Fixed Subnautica not starting in SP via Steam, after starting in MP

NitroxClient/Communication/Packets/Processors/RemoveCreatureCorpseProcessor.cs, NitroxClient/GameLogic/Spawning/Metadata/Processor/EatableMetadataProcessor.cs, NitroxPatcher/Patches/Dynamic/CreatureDeath_OnKillAsync_Patch.cs, NitroxPatcher/Patches/Dynamic/CreatureDeath_SpawnRespawner_Patch.cs, NitroxPatcher/Patches/Dynamic/LiveMixin_TakeDamage_Patch.cs, NitroxServer-Subnautica/GameLogic/Entities/Spawning/SubnauticaEntityBootstrapperManager.cs
Fixes #2260
Step to reproduce : `By putting fishes on the geyser, seeing them die, unload zone and reload the zone`
=> Fix creature respawn duplicating entities

Directory.Build.props, Directory.Build.targets, Nitrox.Launcher/App.axaml.cs, Nitrox.Shared.props, NitroxClient/MonoBehaviours/Gui/InGame/TopRightWatermarkText.cs, NitroxClient/MonoBehaviours/Gui/MainMenu/ServerJoin/JoinServerBackend.cs, NitroxClient/MonoBehaviours/Multiplayer.cs, NitroxModel/Core/NitroxEnvironment.cs, NitroxModel/Extensions.cs, NitroxPatcher/Main.cs, NitroxServer-Subnautica/Program.cs
Embedded git info into project output
Changed version text in-game to contain git hash
Closes #2351
=> Changed version text in-game to contain git hash

Nitrox.Assets.Subnautica/LanguageFiles/en.json, NitroxClient/GameLogic/Spawning/Bases/BuildingPostSpawner.cs
=> Add warning when constructing scanner rooms

Nitrox.Test/Client/Communication/PacketSuppressorTest.cs, NitroxClient/Communication/PacketSuppressor.cs, NitroxClient/GameLogic/Interior.cs, NitroxClient/MonoBehaviours/Cyclops/VirtualCyclops.cs, NitroxPatcher/Patches/Dynamic/Openable_PlayOpenAnimation_Patch.cs
=> Fix crash from OpenableStateChanged packet spamming

Nitrox.Assets.Subnautica/Resources/SoundWhitelist_Subnautica.csv
Maybe also investigate #2392 and #2358 while at it
=> Integrate new sounds from SN update

NitroxClient/GameLogic/Spawning/WorldEntities/PlaceholderGroupWorldEntitySpawner.cs, NitroxServer/GameLogic/Entities/Spawning/BatchEntitySpawner.cs
Needs testing !!! (feedbacks from people building Nitrox on their own would be appreciated on this PR) (only fresh world is meaningful for this PR)
- I could check myself that the crabsnakes and the eggs had a regular case (warp 130 -95 -390)
- I also could check that spawned fragments and stuff at wreck13 were actually spawned under the cellroot and not under the group placeholder (which is the base game's correct behaviour)
- I imported @killzoms fix for floating stones
=> Fix crabsnakes size

.github/workflows/buildingMaster.yml, .github/workflows/buildingPullRequest.yml, .github/workflows/testPullRequest.yml, .github/workflows/testResults.yml, .github/workflows/testingPullRequest.yml, Directory.Build.targets, README.md
Now with the native launcher we can try to add CICD once again.
Currently this solution needs a self hosted runner which I can provide but another wouldn't hurt for reliability
=> ReReAdd github actions

NitroxClient/Helpers/PlanterExtensions.cs, NitroxPatcher/Patches/Dynamic/FruitPlant_Update_Patch.cs
Some condition was too narrow, targetting only bases while cyclops could also be valid owners.
Fixes #2445
=> Fix fruit plant growing in cyclops

NitroxClient/Communication/Packets/Processors/CoffeeMachineUseProcessor.cs
Closes #2466 
Was just a typo in an if statement. No clue how this made it through reviews XD
=> Fix coffee machine sync

Nitrox.Assets.Subnautica/Resources/SoundWhitelist_Subnautica.csv, NitroxClient/Communication/Packets/Processors/SeamothModuleActionProcessor.cs
=> Sync seamoth electrical defense sound
